Repository NationalSecurityAgency/datawave, pull requests merged in 2021-08, with the labels that each got.

#1230 Remove reference to script that does not exist
  warehouse/assemble/datawave/pom.xml
Labels: Integration Tested, accepted

#1226 closes #1225: add uid aggregator that will keep countOnly keys when 0…
  properties/default.properties
  warehouse/ingest-configuration/src/main/resources/config/shard-ingest-config.xml
  warehouse/ingest-core/src/main/java/datawave/ingest/table/aggregator/GlobalIndexUidAggregator.java
  warehouse/ingest-core/src/main/java/datawave/ingest/table/aggregator/KeepCountOnlyUidAggregator.java
  warehouse/ingest-core/src/main/java/datawave/ingest/table/config/ShardTableConfigHelper.java
  warehouse/ingest-core/src/test/java/datawave/ingest/table/aggregator/GlobalIndexUidAggregatorTest.java
  warehouse/ingest-core/src/test/java/datawave/ingest/table/aggregator/KeepCountOnlyUidAggregatorTest.java
  warehouse/ingest-core/src/test/java/datawave/ingest/table/aggregator/UidTestUtils.java
  warehouse/ingest-core/src/test/java/datawave/ingest/table/config/ShardTableConfigHelperTest.java
Labels: Integration Tested, accepted

#1222 fixes #1221: Expose geowave configuration in ShardQueryLogic.
  warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
Labels: bug, Integration Tested, accepted

#1220 fixes #1218: Fixes geo bound precision when converting geo functions …
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/GeoFunctionsDescriptor.java
  warehouse/query-core/src/test/java/datawave/query/jexl/functions/GeoFunctionsDescriptorTest.java
Labels: Integration Tested, accepted

#1209 Fixes #1204 - Ensure that relevant index-only fields are added to the Jexl context
  warehouse/query-core/src/main/java/datawave/query/function/IndexOnlyContextCreator.java
  warehouse/query-core/src/main/java/datawave/query/jexl/DelayedNonEventIndexContext.java
Labels: bug, Integration Tested, accepted

#1132 issue 1062: Allow GROUP_BY to work on multi-value fields
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/transformer/GroupingTransform.java
  warehouse/query-core/src/test/java/datawave/query/transformer/GroupingTest.java
  warehouse/query-core/src/test/java/datawave/query/transformer/GroupingTestWithModel.java
  warehouse/query-core/src/test/java/datawave/query/util/VisibilityWiseGuysIngest.java
Labels: Integration Tested, accepted

#1191 Clean up orphaned partial bulk load directories #1150
  contrib/datawave-quickstart/docker/Dockerfile
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/IngestJob.java
Labels: Integration Tested, accepted

#1197 Add support for further granularity in #UNIQUE
  warehouse/query-core/src/main/java/datawave/query/Constants.java
  warehouse/query-core/src/main/java/datawave/query/attributes/UniqueFields.java
  warehouse/query-core/src/main/java/datawave/query/attributes/UniqueGranularity.java
  warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java
  warehouse/query-core/src/main/java/datawave/query/iterator/QueryOptions.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/QueryFunctions.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryOptionsFromQueryVisitor.java
  warehouse/query-core/src/main/java/datawave/query/language/builder/jexl/JexlTreeBuilder.java
  warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/Unique.java
  warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/UniqueByDay.java
  warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/UniqueByFunction.java
  warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/UniqueByHour.java
  warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/UniqueByMinute.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/planner/QueryOptionsSwitch.java
  warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
  warehouse/query-core/src/main/java/datawave/query/transformer/UniqueTransform.java
  warehouse/query-core/src/test/java/datawave/query/attributes/UniqueFieldsTest.java
  warehouse/query-core/src/test/java/datawave/query/attributes/UniqueGranularityTest.java
  warehouse/query-core/src/test/java/datawave/query/config/ShardQueryConfigurationTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryOptionsFromQueryVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/language/functions/jexl/UniqueTest.java
  warehouse/query-core/src/test/java/datawave/query/language/parser/jexl/TestLuceneToJexlQueryParser.java
  warehouse/query-core/src/test/java/datawave/query/language/parser/lucene/TestLuceneQueryParser.java
  warehouse/query-core/src/test/java/datawave/query/transformer/UniqueTransformTest.java
Labels: Integration Tested, accepted

#1207 fixes #1206: Updated JexlStringBuildingVisitor to correctly render ne…
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/JexlStringBuildingVisitor.java
  warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/ContentFunctionArguments.java
  warehouse/query-core/src/test/java/datawave/query/jexl/functions/ContentFunctionQueryTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/JexlStringBuildingVisitorTest.java
Labels: bug, Integration Tested, accepted

#1067 fix #1051: Hardcode media type used by DatawaveWebApplicationException in the QueryExecutorBean execute method.
  web-services/common-util/src/main/java/datawave/webservice/common/exception/DatawaveWebApplicationException.java
  web-services/query/src/main/java/datawave/webservice/query/runner/QueryExecutorBean.java
Labels: Integration Tested, accepted

#1006 Guard against regex and range expansion by default
  warehouse/query-core/src/main/java/datawave/query/jexl/NodeTypeCount.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/NodeTypeCountVisitor.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/test/java/datawave/query/jexl/NodeTypeCountTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/NodeTypeCountVisitorTest.java
Labels: Integration Tested, accepted

#1240 Accommodate is-null/is-not-null query functions on geo fields (#1239)
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/GeoWavePruningVisitor.java
Labels: Integration Tested, accepted

#1258 Added check for ingest metrics before counter check
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/BulkIngestMapFileLoader.java
Labels: Integration Tested
