Repository NationalSecurityAgency/datawave, pull requests merged in 2021-12, with the labels that each got.

#1358 Fixes issue 1312 - Ensure empty files of different names are ignored …
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/SafeFileOutputCommitter.java
  warehouse/ingest-core/src/test/java/datawave/ingest/mapreduce/job/SafeFileOutputCommitterTest.java
Labels: Integration Tested

#1361 fixes #1360: Updates evaluation only parsing to wrap the argument in …
  warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/EvaluationOnly.java
  warehouse/query-core/src/main/java/datawave/query/language/functions/lucene/EvaluationOnly.java
  warehouse/query-core/src/test/java/datawave/query/language/parser/jexl/TestLuceneToJexlParser.java
Labels: bug, Integration Tested

#1362 fixes #1321: Updates default query planner to run geowave pruning bef…
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
Labels: bug, Integration Tested

#1355 Adding type updates for tokens
  warehouse/ingest-core/src/main/java/datawave/ingest/metadata/EventMetadata.java
  warehouse/ingest-core/src/test/java/datawave/ingest/metadata/EventMetadataTest.java
Labels: Integration Tested

#1366 Add method to JexlASTHelper to validate children of junction nodes
  warehouse/query-core/src/main/java/datawave/query/jexl/JexlASTHelper.java
  warehouse/query-core/src/test/java/datawave/query/jexl/JexlASTHelperTest.java
Labels: Integration Tested, accepted

#1374 fixes #1364 Process all eligible IndexStreams in Union.advanceQueue()
  warehouse/query-core/src/main/java/datawave/query/index/lookup/Intersection.java
  warehouse/query-core/src/main/java/datawave/query/index/lookup/Union.java
  warehouse/query-core/src/test/java/datawave/query/index/lookup/IntersectionTest.java
  warehouse/query-core/src/test/java/datawave/query/index/lookup/RangeStreamTest.java
Labels: Integration Tested, accepted

#1318 Update for MinimalReferenceExpressionsVisitor
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/validate/MinimalReferenceExpressionsVisitor.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/validate/MinimalReferenceExpressionsVisitorTest.java
Labels: Integration Tested
