Repository NationalSecurityAgency/datawave, pull requests merged in 2021-09, with the labels that each got.

#1048 Return singular Instance from QueryPropertyMarkerVisitor
  warehouse/query-core/src/main/java/datawave/query/index/lookup/EntryParser.java
  warehouse/query-core/src/main/java/datawave/query/index/lookup/IndexInfo.java
  warehouse/query-core/src/main/java/datawave/query/index/lookup/RangeStream.java
  warehouse/query-core/src/main/java/datawave/query/jexl/DatawaveInterpreter.java
  warehouse/query-core/src/main/java/datawave/query/jexl/JexlASTHelper.java
  warehouse/query-core/src/main/java/datawave/query/jexl/nodes/BoundedRange.java
  warehouse/query-core/src/main/java/datawave/query/jexl/nodes/ExceededOrThresholdMarkerJexlNode.java
  warehouse/query-core/src/main/java/datawave/query/jexl/nodes/ExceededTermThresholdMarkerJexlNode.java
  warehouse/query-core/src/main/java/datawave/query/jexl/nodes/ExceededValueThresholdMarkerJexlNode.java
  warehouse/query-core/src/main/java/datawave/query/jexl/nodes/IndexHoleMarkerJexlNode.java
  warehouse/query-core/src/main/java/datawave/query/jexl/nodes/QueryPropertyMarker.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/BoundedRangeDetectionVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/DelayedNonEventSubTreeVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/EvaluationRendering.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ExecutableDeterminationVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ExpandCompositeTerms.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ExpandMultiNormalizedTerms.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/FixUnfieldedTermsVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/FunctionIndexQueryExpansionVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/IteratorBuildingVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/IvaratorRequiredVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/NodeTypeCountVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ParallelIndexExpansion.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/PullupUnexecutableNodesVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/PushFunctionsIntoExceededValueRanges.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/PushdownLargeFieldedListsVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/PushdownLowSelectivityNodesVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/PushdownMissingIndexRangeNodesVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/PushdownNegationVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/PushdownUnexecutableNodesVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPropertyMarkerVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/RangeConjunctionRebuildingVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/RootNegationCheckVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/SatisfactionVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/SortedUIDsRequiredVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/TermCountingVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/TreeFlatteningRebuilder.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/UnmarkedBoundedRangeDetectionVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/VariableNameVisitor.java
  warehouse/query-core/src/main/java/datawave/query/language/parser/jexl/JexlNodeSet.java
  warehouse/query-core/src/main/java/datawave/query/planner/pushdown/IsType.java
  warehouse/query-core/src/main/java/datawave/query/planner/pushdown/rules/DelayedPredicatePushDown.java
  warehouse/query-core/src/main/java/datawave/query/planner/rules/NodeTransformVisitor.java
  warehouse/query-core/src/main/java/org/apache/commons/jexl2/parser/ASTDelayedPredicate.java
  warehouse/query-core/src/main/java/org/apache/commons/jexl2/parser/ASTEvaluationOnly.java
  warehouse/query-core/src/test/java/datawave/query/jexl/nodes/QueryPropertyMarkerTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ExecutableDeterminationVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/FieldToFieldComparisonVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryPropertyMarkerVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/planner/rules/NodeTransformVisitorTest.java
Labels: Integration Tested, accepted

#1244 Support setting SHARDS_AND_DAYS hint from options function
  warehouse/query-core/src/main/java/datawave/query/QueryParameters.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/AddShardsAndDaysVisitor.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/AddShardsAndDaysVisitorTest.java
Labels: Integration Tested, accepted

#1265 Verify lineage for QueryOptionsFromQueryVisitor
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryOptionsFromQueryVisitor.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryOptionsFromQueryVisitorTest.java
Labels: Integration Tested, accepted

#1266 Fix lineage for FixUnindexedNumericTerms
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/FixUnindexedNumericTerms.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/FixUnindexedNumericTermsTest.java
Labels: Integration Tested, accepted

#1267 Fix lineage for FieldToFieldComparisonVisitor
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/FieldToFieldComparisonVisitor.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/FieldToFieldComparisonVisitorTest.java
Labels: Integration Tested, accepted

#1268 Verify lineage for NodeTransformVisitor
  warehouse/query-core/src/test/java/datawave/query/planner/rules/NodeTransformVisitorTest.java
Labels: Integration Tested, accepted

#1280 Improve test names in HasTopLevelNegationVisitorTest
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/HasTopLevelNegationVisitorTest.java
Labels: Integration Tested, accepted

#1281 Make tests in SatisfactionVisitorTest easier to read
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/SatisfactionVisitorTest.java
Labels: Integration Tested, accepted

#1282 Make tests in HasUnfieldedTermsVisitorTest easier to read
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/HasUnfieldedTermVisitorTest.java
Labels: Integration Tested, accepted

#1283 Make tests in HashMethodVisitorTest easier to read
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/HasMethodVisitorTest.java
Labels: Integration Tested, accepted

#1284 Add custom assertions for JexlNode instances
  pom.xml
  warehouse/query-core/pom.xml
  warehouse/query-core/src/main/java/datawave/query/jexl/JexlASTHelper.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/AllTermsIndexedVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/BooleanOptimizationRebuildingVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/CaseSensitivityVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ConjunctionEliminationVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/DateIndexCleanupVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/DateIndexQueryExpansionVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/DisjunctionEliminationVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ExpandCompositeTermsTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ExpandMultiNormalizedTermsTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/FieldToFieldComparisonVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/FixNegativeNumbersVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/FunctionIndexQueryExpansionVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/GeoWavePruningVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/IsNotNullIntentVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryModelVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/RegexFunctionVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/TreeFlatteningRebuildingVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/TreeWrappingRebuildingVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/UniqueExpressionTermsVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/tables/facets/FacetCheckTest.java
  warehouse/query-core/src/test/java/datawave/test/JexlNodeAssert.java
Labels: Integration Tested

#1194 Don't drop UIDs in GlobalIndexUidAggregator
  warehouse/core/src/main/java/datawave/ingest/protobuf/Uid.java
  warehouse/core/src/main/protobuf/Uid.proto
  warehouse/ingest-core/src/main/java/datawave/ingest/table/aggregator/GlobalIndexUidAggregator.java
  warehouse/ingest-core/src/main/java/datawave/ingest/table/aggregator/KeepCountOnlyUidAggregator.java
  warehouse/ingest-core/src/main/java/datawave/iterators/PropogatingIterator.java
  warehouse/ingest-core/src/test/java/datawave/ingest/table/aggregator/GlobalIndexUidAggregatorExpandedTest.java
  warehouse/ingest-core/src/test/java/datawave/ingest/table/aggregator/GlobalIndexUidAggregatorTest.java
  warehouse/ingest-core/src/test/java/datawave/ingest/table/aggregator/UidTestBuilder.java
  warehouse/ingest-core/src/test/java/datawave/ingest/table/aggregator/UidTestUtils.java
  warehouse/ingest-core/src/test/java/datawave/iterators/PropogatingIteratorSeekTest.java
  warehouse/ingest-core/src/test/java/datawave/iterators/PropogatingIteratorTest.java
Labels: Integration Tested, accepted

#1212 closes #1210: Added a Whindex (value-specific) field mapping visitor.
  warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctionsDescriptor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ExpandCompositeTerms.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/whindex/DistributeAndedNodesVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/whindex/SplitGeoWaveFunctionVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/whindex/WhindexTerm.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/whindex/WhindexVisitor.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
  warehouse/query-core/src/main/java/datawave/query/tables/async/event/VisitorFunction.java
  warehouse/query-core/src/test/java/datawave/query/config/ShardQueryConfigurationTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/WhindexVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/tables/async/event/VisitorFunctionTest.java
Labels: Integration Tested, accepted

#1242 Clean up shard-day-hint negations in DateIndexCleanupVisitor as required (#1241)
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/DateIndexCleanupVisitor.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/DateIndexCleanupVisitorTest.java
Labels: bug, Integration Tested, accepted

#1247 Wait for ingest servers to stop before killing jobs
  warehouse/ingest-scripts/src/main/resources/bin/ingest/stop-ingest-servers.sh
  warehouse/ingest-scripts/src/main/resources/bin/util/pid-functions.sh
Labels: Integration Tested, accepted

#1261 Re: Issue #454 - added FullTableScanDisallowedException
  warehouse/query-core/src/test/java/datawave/query/MaxExpansionIndexOnlyQueryTest.java
Labels: Integration Tested, accepted

#1211 closes #1166: Adds ability to query Geo fields with GeoWave functions.
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/GeoFunctionsDescriptor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/GeoWaveFunctions.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/GeoWaveFunctionsDescriptor.java
  warehouse/query-core/src/test/java/datawave/query/MixedGeoAndGeoWaveTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/functions/GeoWaveFunctionsDescriptorTest.java
Labels: Integration Tested, accepted
