Repository NationalSecurityAgency/datawave, pull requests merged in 2021-11, with the labels that each got.

#1336 fixes #1334: Intersection.next() should validate next is consistent w…
  warehouse/query-core/src/main/java/datawave/query/index/lookup/Intersection.java
  warehouse/query-core/src/test/java/datawave/query/index/lookup/IntersectionTest.java
Labels: Integration Tested, accepted

#1319 Integrate additional validating visitors into the ASTValidator
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/validate/ASTValidator.java
Labels: Integration Tested

#1329 Add #NOEXPANSION function
  warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/ContentFunctionsDescriptor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctionsDescriptor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/NoExpansionFunctionVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryModelVisitor.java
  warehouse/query-core/src/main/java/datawave/query/language/builder/jexl/JexlTreeBuilder.java
  warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/NoExpansion.java
  warehouse/query-core/src/main/java/datawave/query/language/processor/lucene/CustomFieldLimiterNodeProcessor.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/test/java/datawave/query/config/ShardQueryConfigurationTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/FunctionIndexQueryExpansionVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/NoExpansionFunctionVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryModelVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/language/parser/jexl/TestLuceneToJexlParser.java
Labels: Integration Tested

#1320 Improve test coverage of EvaluationPhaseFilterFunctions
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctions.java
  warehouse/query-core/src/test/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctionsTest.java
Labels: Integration Tested, accepted

#1195 Fixes #879 - X-Partial Status
  web-services/query/src/main/java/datawave/webservice/query/runner/RunningQuery.java
  web-services/query/src/test/java/datawave/webservice/query/runner/ExtendedRunningQueryTest.java
Labels: accepted

#1333 Add support for parsing #COMPARE function from lucene query
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/CompareFunctionValidator.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctions.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctionsDescriptor.java
  warehouse/query-core/src/main/java/datawave/query/language/builder/jexl/JexlTreeBuilder.java
  warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/Compare.java
  warehouse/query-core/src/main/java/datawave/query/language/processor/lucene/CustomFieldLimiterNodeProcessor.java
  warehouse/query-core/src/test/java/datawave/query/LuceneQueryTest.java
  warehouse/query-core/src/test/java/datawave/query/function/JexlEvaluationTest.java
  warehouse/query-core/src/test/java/datawave/query/language/parser/jexl/TestLuceneToJexlQueryParser.java
  warehouse/query-core/src/test/java/datawave/query/testframework/QueryJexl.java
  warehouse/query-core/src/test/resources/datawave/query/EventQueryLogicFactory.xml
  warehouse/query-core/src/test/resources/datawave/query/QueryLogicFactory.xml
  web-services/deploy/docs/docs/query_help.html
Labels: Integration Tested

#1341 Merge filter matchPatterns across classes
  warehouse/core/src/main/java/datawave/ingest/util/cache/watch/FileRuleWatcher.java
  warehouse/core/src/main/java/datawave/iterators/filter/RegexFilterBase.java
  warehouse/core/src/main/java/datawave/iterators/filter/TokenSpecParser.java
  warehouse/core/src/main/java/datawave/iterators/filter/TokenTtlTrie.java
  warehouse/core/src/main/java/datawave/iterators/filter/TokenizingFilterBase.java
  warehouse/core/src/test/java/datawave/ingest/util/cache/watch/DifferentClassesMergeTest.java
  warehouse/core/src/test/java/datawave/ingest/util/cache/watch/TestTrieFilter.java
  warehouse/core/src/test/java/datawave/iterators/filter/ColumnVisibilityLabeledFilter.java
  warehouse/core/src/test/java/datawave/iterators/filter/TokenTtlTrieTest.java
  warehouse/core/src/test/resources/alternate-child.xml
  warehouse/core/src/test/resources/alternate-root.xml
Labels: Integration Tested

#1297 Fix reparented query property marker bug
  warehouse/query-core/src/main/java/datawave/query/jexl/nodes/BoundedRange.java
  warehouse/query-core/src/main/java/datawave/query/jexl/nodes/ExceededOrThresholdMarkerJexlNode.java
  warehouse/query-core/src/main/java/datawave/query/jexl/nodes/ExceededTermThresholdMarkerJexlNode.java
  warehouse/query-core/src/main/java/datawave/query/jexl/nodes/ExceededValueThresholdMarkerJexlNode.java
  warehouse/query-core/src/main/java/datawave/query/jexl/nodes/IndexHoleMarkerJexlNode.java
  warehouse/query-core/src/main/java/datawave/query/jexl/nodes/QueryPropertyMarker.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPropertyMarkerSourceConsolidator.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPropertyMarkerVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/TermCountingVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/TreeFlatteningRebuilder.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/validate/ValidQueryPropertyMarkerVisitor.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/main/java/org/apache/commons/jexl2/parser/ASTDelayedPredicate.java
  warehouse/query-core/src/main/java/org/apache/commons/jexl2/parser/ASTEvaluationOnly.java
  warehouse/query-core/src/test/java/datawave/query/LuceneQueryTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/nodes/QueryPropertyMarkerTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryPropertyMarkerSourceConsolidatorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryPropertyMarkerVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/validate/ValidQueryPropertyMarkerVisitorTest.java
  warehouse/query-core/src/test/java/datawave/test/DeepJexlNodeComparator.java
  warehouse/query-core/src/test/java/datawave/test/JexlNodeAssert.java
  warehouse/query-core/src/test/java/datawave/test/JexlNodeAssertions.java
  warehouse/query-core/src/test/java/datawave/test/JexlNodeIterableAssert.java
  warehouse/query-core/src/test/java/datawave/test/JexlNodeListAssert.java
  warehouse/query-core/src/test/java/datawave/test/ShallowJexlNodeComparator.java
Labels: Integration Tested, accepted

#1346 Apply UID maximum to removal list
  warehouse/ingest-core/src/main/java/datawave/ingest/table/aggregator/GlobalIndexUidAggregator.java
  warehouse/ingest-core/src/test/java/datawave/ingest/table/aggregator/GlobalIndexUidAggregatorExpandedTest.java
Labels: Integration Tested

#1351 fixes #1315: Updated to use the scan limit only between returning keys
  warehouse/query-core/src/main/java/datawave/core/iterators/ColumnFamilyRangeIterator.java
  warehouse/query-core/src/main/java/datawave/core/iterators/ColumnQualifierRangeIterator.java
  warehouse/query-core/src/main/java/datawave/core/iterators/ColumnRangeIterator.java
  warehouse/query-core/src/main/java/datawave/query/tables/edge/EdgeQueryLogic.java
  warehouse/query-core/src/test/java/datawave/query/edge/ExtendedEdgeQueryLogicTest.java
  warehouse/query-core/src/test/java/datawave/query/tables/edge/BaseEdgeQueryTest.java
Labels: Integration Tested, accepted

#1260 fixes #1259: Updated to include the DOTALL flag for patterns.
  warehouse/query-core/src/main/java/datawave/query/jexl/JexlPatternCache.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctionsDescriptor.java
  warehouse/query-core/src/main/java/datawave/query/planner/rules/RegexDotallTransformRule.java
  warehouse/query-core/src/main/java/datawave/query/planner/rules/RegexPushdownTransformRule.java
  warehouse/query-core/src/main/java/datawave/query/planner/rules/RegexReplacementTransformRule.java
  warehouse/query-core/src/main/java/datawave/query/planner/rules/RegexSimplifierTransformRule.java
  warehouse/query-core/src/test/java/datawave/query/jexl/JexlPatternCacheTest.java
  warehouse/query-core/src/test/java/datawave/query/planner/rules/NodeTransformVisitorTest.java
Labels: Integration Tested, accepted
