Repository NationalSecurityAgency/datawave, pull requests merged in 2022-04, with the labels that each got.

#1480 Remove deprecated ConfigurableEventDataQueryFilter
  warehouse/query-core/src/main/java/datawave/query/predicate/ConfigurableEventDataQueryFilter.java
Labels: Integration Tested

#1431 Fixes #1430 Added separate term threshold limits for use before and a…
  properties/default.properties
  warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
  warehouse/query-core/src/main/java/datawave/query/tables/async/event/VisitorFunction.java
  warehouse/query-core/src/test/java/datawave/query/MiscQueryTest.java
  warehouse/query-core/src/test/java/datawave/query/config/ShardQueryConfigurationTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ExecutableExpansionVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/planner/CompositeIndexTest.java
  warehouse/query-core/src/test/java/datawave/query/tables/async/event/VisitorFunctionTest.java
  warehouse/query-core/src/test/resources/datawave/query/EventQueryLogicFactory.xml
  warehouse/query-core/src/test/resources/datawave/query/QueryLogicFactory.xml
  web-services/deploy/configuration/src/main/resources/datawave/query/QueryLogicFactory.xml
Labels: Integration Tested

#1488 Add visitor to prune IsNotNull terms when possible.
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/IsNotNullPruningVisitor.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/main/java/org/apache/commons/jexl2/parser/JexlNodes.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/IsNotNullPruningVisitorTest.java
  warehouse/query-core/src/test/java/org/apache/commons/jexl2/parser/JexlNodesTest.java
Labels: Integration Tested

#1481 Add test cases for Projection, KeyProjection and DocumentProjection
  warehouse/query-core/src/main/java/datawave/query/function/DocumentProjection.java
  warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/facets/DynamicFacetIterator.java
  warehouse/query-core/src/main/java/datawave/query/predicate/EventDataQueryFieldFilter.java
  warehouse/query-core/src/main/java/datawave/query/predicate/KeyProjection.java
  warehouse/query-core/src/main/java/datawave/query/predicate/Projection.java
  warehouse/query-core/src/test/java/datawave/query/function/DocumentProjectionTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/functions/TermFrequencyAggregatorTest.java
  warehouse/query-core/src/test/java/datawave/query/predicate/KeyProjectionTest.java
  warehouse/query-core/src/test/java/datawave/query/predicate/ProjectionTest.java
Labels: Integration Tested

#1482 Add term frequency excerpts to results
  warehouse/query-core/src/main/java/datawave/query/Constants.java
  warehouse/query-core/src/main/java/datawave/query/QueryParameters.java
  warehouse/query-core/src/main/java/datawave/query/attributes/ExcerptFields.java
  warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java
  warehouse/query-core/src/main/java/datawave/query/function/JexlEvaluation.java
  warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/QueryOptions.java
  warehouse/query-core/src/main/java/datawave/query/iterator/logic/TermFrequencyExcerptIterator.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/ContentFunctionEvaluator.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/ContentFunctions.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/ContentOrderedEvaluator.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/ContentUnorderedEvaluator.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/QueryFunctions.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/QueryFunctionsDescriptor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryOptionsFromQueryVisitor.java
  warehouse/query-core/src/main/java/datawave/query/language/builder/jexl/JexlTreeBuilder.java
  warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/ExcerptFields.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/planner/QueryOptionsSwitch.java
  warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/PhraseIndexes.java
  warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TermOffsetMap.java
  warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TermOffsetPopulator.java
  warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
  warehouse/query-core/src/main/java/datawave/query/transformer/ExcerptTransform.java
  warehouse/query-core/src/test/java/datawave/query/attributes/ExcerptFieldsTest.java
  warehouse/query-core/src/test/java/datawave/query/config/ShardQueryConfigurationTest.java
  warehouse/query-core/src/test/java/datawave/query/function/JexlEvaluationTest.java
  warehouse/query-core/src/test/java/datawave/query/iterator/logic/TermFrequencyExcerptIteratorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/functions/ContentFunctionsTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/functions/ContentOrderedEvaluatorTest.java
  warehouse/query-core/src/test/java/datawave/query/postprocessing/tf/PhraseIndexesTest.java
  warehouse/query-core/src/test/java/datawave/query/transformer/ExcerptTransformTest.java
  web-services/deploy/configuration/src/main/resources/datawave/query/QueryLogicFactory.xml
Labels: Integration Tested, accepted

#1486 re #1485 Use ArrayList instead of LinkedHashSet in DatawavePrincipal, maintain chronological order
  web-services/common-util/src/main/java/datawave/security/authorization/DatawavePrincipal.java
  web-services/common-util/src/main/java/datawave/security/util/DnUtils.java
  web-services/common-util/src/test/java/datawave/security/authorization/DatawavePrincipalTest.java
  web-services/common-util/src/test/java/datawave/security/util/AuthorizationsUtilTest.java
  web-services/common-util/src/test/java/datawave/security/util/DnUtilsTest.java
  web-services/security/src/main/java/datawave/security/auth/DatawaveCredential.java
  web-services/security/src/test/java/datawave/security/auth/DatawaveAuthenticationMechanismTest.java
  web-services/security/src/test/java/datawave/security/login/DatawavePrincipalLoginModuleTest.java
Labels: Integration Tested

#1520 Handle exception thrown when retrieving excerpts for TLDEventQuery
  warehouse/query-core/src/main/java/datawave/query/transformer/ExcerptTransform.java
Labels: Integration Tested, accepted

#1514 fixes #1511 Replaced the visitor function hashmap with a size-limited…
  warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java
  warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
  warehouse/query-core/src/main/java/datawave/query/tables/async/event/VisitorFunction.java
  warehouse/query-core/src/test/java/datawave/query/config/ShardQueryConfigurationTest.java
Labels: bug, enhancement, Integration Tested

#1489 Adding new role for max query result override
  web-services/query/src/main/java/datawave/webservice/query/runner/BasicQueryBean.java
  web-services/query/src/main/java/datawave/webservice/query/runner/QueryExecutorBean.java
Labels: Integration Tested
