Repository NationalSecurityAgency/datawave, pull requests merged in 2022-01, with the labels that each got.

#1381 Fix circular parent reference
  warehouse/query-core/src/main/java/datawave/query/jexl/JexlNodeFactory.java
Labels: Integration Tested

#1347 Date volume chooser
  docs/pom.xml
  warehouse/accumulo-extensions/pom.xml
  warehouse/accumulo-extensions/src/main/java/datawave/ingest/table/balancer/ShardedTableTabletBalancer.java
  warehouse/accumulo-extensions/src/main/java/datawave/ingest/table/balancer/package-info.java
  warehouse/accumulo-extensions/src/main/java/datawave/ingest/table/volumeChoosers/ShardedTableDateBasedTieredVolumeChooser.java
  warehouse/accumulo-extensions/src/test/java/datawave/ingest/table/balancer/ShardedTableTabletBalancerTest.java
  warehouse/accumulo-extensions/src/test/java/datawave/ingest/table/volumeChoosers/ShardedTableDateBasedTieredVolumeChooserTest.java
  warehouse/assemble/datawave/pom.xml
  warehouse/assemble/datawave/src/main/assembly/dist.xml
  warehouse/ingest-core/pom.xml
  warehouse/ingest-scripts/src/main/resources/bin/ingest/findJars.sh
  warehouse/pom.xml
Labels: accepted

#1384 Create OperatorEvaluator utilities class
  warehouse/core/src/main/java/datawave/util/OperationEvaluator.java
  warehouse/core/src/test/java/datawave/util/OperationEvaluatorTest.java
  warehouse/query-core/src/main/java/datawave/query/collections/FunctionalSet.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctions.java
  warehouse/query-core/src/test/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctionsTest.java
Labels: Integration Tested, accepted

#1379 Ensure unique_by_xxx functions are allowed
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/QueryFunctionsDescriptor.java
  web-services/deploy/configuration/src/main/resources/datawave/query/QueryLogicFactory.xml
Labels: Integration Tested, accepted

#1371 Fix occurrence query function
  warehouse/query-core/src/main/java/datawave/query/attributes/Attribute.java
  warehouse/query-core/src/main/java/datawave/query/attributes/Document.java
  warehouse/query-core/src/main/java/datawave/query/function/Aggregation.java
  warehouse/query-core/src/main/java/datawave/query/function/IndexOnlyKeyToDocumentData.java
  warehouse/query-core/src/main/java/datawave/query/function/KeyToDocumentData.java
  warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/aggregation/DocumentData.java
  warehouse/query-core/src/main/java/datawave/query/iterator/facets/DynamicFacetIterator.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctions.java
  warehouse/query-core/src/main/java/datawave/query/predicate/ValueToAttributes.java
  warehouse/query-core/src/test/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctionsTest.java
  warehouse/query-core/src/test/java/datawave/query/predicate/ValueToAttributesTest.java
Labels: Integration Tested, accepted

#1399 DATAWAVE-1395: Updated the virtual field generation to more effecient…
  warehouse/ingest-core/src/main/java/datawave/ingest/data/config/ingest/VirtualIngest.java
  warehouse/ingest-core/src/test/java/datawave/ingest/data/config/ingest/VirtualFieldTest.java
Labels: Integration Tested, accepted
