Repository NationalSecurityAgency/datawave, pull requests merged in 2023-12, with the labels that each got.

#2182 * Updated to supply more logging around filtered logics/user operations
  warehouse/query-core/src/main/java/datawave/query/tables/RemoteEventQueryLogic.java
  web-services/query/src/main/java/datawave/webservice/query/logic/composite/CompositeQueryLogic.java
  web-services/query/src/main/java/datawave/webservice/query/logic/filtered/FilteredQueryLogic.java
  web-services/query/src/main/java/datawave/webservice/query/logic/filtered/QueryLogicFilterByAuth.java
  web-services/query/src/main/java/datawave/webservice/query/logic/filtered/QueryLogicFilterByParameter.java
  web-services/query/src/main/java/datawave/webservice/query/predicate/AuthorizationsPredicate.java
  web-services/query/src/main/java/datawave/webservice/query/predicate/ProxiedAuthorizationsPredicate.java
  web-services/query/src/main/java/datawave/webservice/query/predicate/QueryParameterPredicate.java
  web-services/security/src/main/java/datawave/security/authorization/remote/ConditionalRemoteUserOperations.java
Labels: Integration Tested, accepted

#2155 better TLD parsing and clean related classes
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/CardinalityAggregator.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/IdentityAggregator.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/TLDEventFieldAggregator.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/TermFrequencyAggregator.java
  warehouse/query-core/src/main/java/datawave/query/predicate/TLDEventDataFilter.java
  warehouse/query-core/src/main/java/datawave/query/tld/TLD.java
  warehouse/query-core/src/main/java/datawave/query/tld/TLDFieldIndexAggregator.java
  warehouse/query-core/src/main/java/datawave/query/tld/TLDTermFrequencyAggregator.java
  warehouse/query-core/src/test/java/datawave/query/predicate/TLDEventDataFilterTest.java
  warehouse/query-core/src/test/java/datawave/query/tld/TLDTermFrequencyAggregatorTest.java
  warehouse/query-core/src/test/java/datawave/query/tld/TLDTest.java
Labels: enhancement, Integration Tested

#2183 Fix Marker Pruning
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/IngestTypePruningVisitor.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/IngestTypePruningVisitorTest.java
Labels: Integration Tested

#2184 Only serialize excerpt options if excerpts are requested
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
Labels: Integration Tested

#2188 Inject updated iterator environment into ConfigurableAgeOffFilter Rules
  warehouse/core/src/main/java/datawave/iterators/filter/ConfigurableAgeOffFilter.java
  warehouse/core/src/main/java/datawave/iterators/filter/ageoff/AppliedRule.java
  warehouse/core/src/main/java/datawave/iterators/filter/ageoff/FilterRule.java
  warehouse/core/src/test/java/datawave/ingest/util/cache/watch/TestFilter.java
  warehouse/core/src/test/java/datawave/iterators/filter/ConfigurableAgeOffFilterTest.java
  warehouse/core/src/test/java/datawave/iterators/filter/ageoff/FieldAgeOffFilterTest.java
  warehouse/query-core/src/main/java/datawave/query/jexl/JexlRule.java
Labels: Integration Tested

#2202 Updated to fill out the query parameters prior to creating Query object
  web-services/query/src/main/java/datawave/webservice/query/util/LookupUUIDUtil.java
  web-services/query/src/test/java/datawave/webservice/query/util/LookupUUIDUtilTest.java
Labels: Integration Tested, accepted

#2194 Fixes ProcessUtils class (#2193)
  common-test/src/main/java/datawave/common/test/utils/ProcessUtils.java
Labels: bug, enhancement

#2204 Updated to use all auths on preinitialization for lookupuuid util
  web-services/query/src/main/java/datawave/webservice/query/util/LookupUUIDUtil.java
Labels: Integration Tested, accepted

#2185 Add hit term call out in excerpt fields
  warehouse/query-core/src/main/java/datawave/query/iterator/QueryOptions.java
  warehouse/query-core/src/main/java/datawave/query/iterator/logic/TermFrequencyExcerptIterator.java
  warehouse/query-core/src/main/java/datawave/query/transformer/ExcerptTransform.java
  warehouse/query-core/src/test/java/datawave/query/attributes/ExcerptFieldsTest.java
  warehouse/query-core/src/test/java/datawave/query/transformer/ExcerptTransformTest.java
Labels: Integration Tested
