Repository NationalSecurityAgency/datawave, pull requests merged in 2023-08, with the labels that each got.

#2053 re #2008: Make the default normalization expansions as they were before
  pom.xml
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ExpandMultiNormalizedTerms.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryModelVisitor.java
  warehouse/query-core/src/test/java/datawave/query/LenientFieldsTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ExpandMultiNormalizedTermsTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryModelVisitorTest.java
Labels: Integration Tested, accepted, linked

#2000 Refactor EventDataQueryFieldFilter
  warehouse/query-core/src/main/java/datawave/query/iterator/facets/DynamicFacetIterator.java
  warehouse/query-core/src/main/java/datawave/query/predicate/EventDataQueryFieldFilter.java
  warehouse/query-core/src/test/java/datawave/query/jexl/functions/TermFrequencyAggregatorTest.java
Labels: Integration Tested

#2058 eliminate duplicate normalization when fetching term offsets
  warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TFFactory.java
  warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TermOffsetPopulator.java
Labels: Integration Tested

#2004 Updated first()/last() methods to not rely on a boolean, clean up
  warehouse/query-core/src/main/java/datawave/query/util/sortedset/FileSortedSet.java
Labels: Integration Tested

#1996 Investigate and update MultiSetBackedSortedSet isEmpty(), first(), and last()
  warehouse/query-core/src/main/java/datawave/query/util/sortedset/MultiSetBackedSortedSet.java
  warehouse/query-core/src/test/java/datawave/query/util/sortedset/MultiSetBackedSortedSetTest.java
Labels: Integration Tested

#1941 Allowing configurable shards per table for tomorrow shards script
  warehouse/ingest-scripts/src/main/resources/bin/ingest/create-tomorrows-shards.sh
  warehouse/ingest-scripts/src/main/resources/bin/ingest/ingest-env.sh
Labels: Integration Tested, linked

#1956 1954 finalize-termfrequency-changes
  warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java
  warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TermFrequencyConfig.java
Labels: Integration Tested, accepted

#1820 1819 - remove unused "warehouse/common-test" module/1 class
  warehouse/common-test/src/main/java/datawave/common/test/utils/query/TestQueries.java
Labels: Integration Tested

#1808 1798 - Fix the Ciritcal Issues Found by SonarQube
  warehouse/core/src/main/java/datawave/ingest/protobuf/TermWeightPosition.java
  warehouse/core/src/main/java/datawave/ingest/util/cache/Loader.java
  warehouse/core/src/main/java/datawave/iterators/filter/ConfigurableAgeOffFilter.java
  warehouse/core/src/main/java/datawave/iterators/filter/TokenSpecParser.java
  warehouse/core/src/main/java/datawave/iterators/filter/ageoff/DataTypeAgeOffFilter.java
  warehouse/core/src/main/java/datawave/mr/bulk/BulkInputFormat.java
  warehouse/core/src/main/java/datawave/util/CounterDump.java
  warehouse/core/src/test/java/datawave/data/hash/SnowflakeUIDTest.java
  warehouse/ingest-core/src/main/java/datawave/ingest/data/config/ingest/CompositeIngest.java
  warehouse/ingest-core/src/main/java/datawave/ingest/data/tokenize/TokenSearchSynonymFilter.java
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/edge/ProtobufEdgeDataTypeHandler.java
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/tokenize/ContentIndexingColumnBasedHandler.java
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/IngestJob.java
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/ShardedTableMapFile.java
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/metrics/ReusableMetricsLabels.java
  warehouse/ingest-core/src/main/java/datawave/ingest/table/aggregator/GlobalIndexUidAggregator.java
  warehouse/ingest-core/src/main/java/datawave/ingest/util/WeightedValuePruningStrategy.java
  warehouse/ingest-core/src/main/java/datawave/util/flag/FlagMaker.java
  warehouse/ingest-core/src/test/java/datawave/ingest/mapreduce/job/BulkIngestMapFileLoaderTest.java
  warehouse/ingest-core/src/test/java/datawave/ingest/mapreduce/partition/MultiTableRRRangePartitionerTest.java
  warehouse/ingest-json/src/main/java/datawave/ingest/json/mr/input/JsonRecordReader.java
  warehouse/ingest-nyctlc/src/main/java/datawave/ingest/nyctlc/NYCTLCIngestHelper.java
  warehouse/ingest-wikipedia/src/main/java/datawave/ingest/wikipedia/WikipediaPageExtractor.java
  warehouse/metrics-core/src/main/java/datawave/metrics/analytic/IngestMetricsSummaryLoader.java
  warehouse/metrics-core/src/main/java/datawave/metrics/util/UpgradeCounterValues.java
  warehouse/query-core/src/main/java/datawave/core/iterators/DatawaveFieldIndexCachingIteratorJexl.java
  warehouse/query-core/src/main/java/datawave/query/index/stats/IndexStatsCombiningIterator.java
  warehouse/query-core/src/main/java/datawave/query/tables/async/event/VisitorFunction.java
Labels: Integration Tested
