Repository NationalSecurityAgency/datawave, pull requests merged in 2023-07, with the labels that each got.

#2015 Fixed incorrect argument to planQuery
  warehouse/query-core/src/main/java/datawave/query/tables/RemoteEventQueryLogic.java
Labels: Integration Tested

#1992 Fix view name
  pom.xml
  warehouse/query-core/pom.xml
  warehouse/query-core/src/main/java/datawave/query/tables/content/ContentQueryTable.java
  warehouse/query-core/src/test/java/datawave/query/tables/content/ContentQueryTableTest.java
  web-services/deploy/spring-framework-integration/src/test/java/datawave/springframework/integration/WiredQueryExecutorBeanTest.java
Labels: Integration Tested

#2003 Only configure excerpt query options when necessary
  warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
  warehouse/query-core/src/main/java/datawave/query/tables/async/event/VisitorFunction.java
  warehouse/query-core/src/test/java/datawave/query/config/ShardQueryConfigurationTest.java
  warehouse/query-core/src/test/resources/datawave/query/QueryLogicFactory.xml
Labels: Integration Tested

#2016 Improving start loader script function
  warehouse/ingest-scripts/src/main/resources/bin/ingest/start-loader.sh
Labels: Integration Tested

#2019 Feature/datawave 2008
  pom.xml
  warehouse/query-core/src/main/java/datawave/query/jexl/JexlNodeFactory.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ExpandMultiNormalizedTerms.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryModelVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPropertyMarkerVisitor.java
  warehouse/query-core/src/main/java/datawave/query/model/util/LoadModelFromXml.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/util/cache/QueryModelLoader.java
  warehouse/query-core/src/main/java/org/apache/commons/jexl2/parser/StrictExpression.java
  warehouse/query-core/src/test/java/datawave/query/AnyFieldQueryTest.java
  warehouse/query-core/src/test/java/datawave/query/LenientFieldsTest.java
  warehouse/query-core/src/test/java/datawave/query/config/ShardQueryConfigurationTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ExpandMultiNormalizedTermsTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryModelVisitorTest.java
  web-services/client/src/main/java/datawave/webservice/model/Model.java
Labels: linked

#1608 Do not consider wrapped/unwrapped query property markers equal
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/TreeEqualityVisitor.java
  warehouse/query-core/src/test/java/datawave/query/index/lookup/RangeStreamTestX.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/TreeEqualityVisitorTest.java
Labels: accepted

#1641 Limit gathered phrase indexes to excerpt fields
  warehouse/query-core/src/main/java/datawave/query/function/JexlEvaluation.java
  warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/ContentOrderedEvaluator.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/ContentUnorderedEvaluator.java
  warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TermOffsetMap.java
  warehouse/query-core/src/test/java/datawave/query/jexl/functions/ContentFunctionsTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/functions/ContentOrderedEvaluatorTest.java
Labels: accepted
