Repository NationalSecurityAgency/datawave, pull requests merged in 2023-10, with the labels that each got.

#2086 Feature/clean up projection classes for deprecation plan
  warehouse/query-core/src/main/java/datawave/query/function/DocumentProjection.java
  warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/facets/DynamicFacetIterator.java
  warehouse/query-core/src/main/java/datawave/query/predicate/EventDataQueryFieldFilter.java
  warehouse/query-core/src/main/java/datawave/query/predicate/KeyProjection.java
  warehouse/query-core/src/main/java/datawave/query/predicate/Projection.java
  warehouse/query-core/src/test/java/datawave/query/function/DocumentProjectionTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/functions/TermFrequencyAggregatorTest.java
  warehouse/query-core/src/test/java/datawave/query/predicate/FieldNameFilterTest.java
  warehouse/query-core/src/test/java/datawave/query/predicate/KeyProjectionTest.java
  warehouse/query-core/src/test/java/datawave/query/predicate/ProjectionTest.java
Labels: Integration Tested

#2085 SSDeepSimilarityQueryLogic implementation
  warehouse/query-core/src/main/java/datawave/query/config/SSDeepSimilarityQueryConfiguration.java
  warehouse/query-core/src/main/java/datawave/query/tables/SSDeepSimilarityQueryLogic.java
  warehouse/query-core/src/main/java/datawave/query/transformer/SSDeepSimilarityQueryTransformer.java
  warehouse/query-core/src/main/java/datawave/query/util/ssdeep/BucketAccumuloKeyGenerator.java
  warehouse/query-core/src/main/java/datawave/query/util/ssdeep/ChunkSizeEncoding.java
  warehouse/query-core/src/main/java/datawave/query/util/ssdeep/HashReverse.java
  warehouse/query-core/src/main/java/datawave/query/util/ssdeep/IntegerEncoding.java
  warehouse/query-core/src/main/java/datawave/query/util/ssdeep/NGramByteHashGenerator.java
  warehouse/query-core/src/main/java/datawave/query/util/ssdeep/NGramGenerator.java
  warehouse/query-core/src/main/java/datawave/query/util/ssdeep/NGramScoreTuple.java
  warehouse/query-core/src/main/java/datawave/query/util/ssdeep/NGramTuple.java
  warehouse/query-core/src/main/java/datawave/query/util/ssdeep/SSDeepEncoding.java
  warehouse/query-core/src/main/java/datawave/query/util/ssdeep/SSDeepHash.java
  warehouse/query-core/src/main/java/datawave/query/util/ssdeep/SSDeepHashParser.java
  warehouse/query-core/src/main/java/datawave/query/util/ssdeep/SSDeepParseException.java
  warehouse/query-core/src/test/java/datawave/query/SSDeepQueryTest.java
  warehouse/query-core/src/test/java/datawave/query/transformer/SSDeepSimilarityQueryTransformerTest.java
  web-services/deploy/configuration/src/main/resources/datawave/query/SSDeepQueryLogicFactory.xml
Labels: Integration Tested

#2116 remove unnecessary method from ingesthelper and clean test pt2
  warehouse/ingest-core/src/main/java/datawave/ingest/data/config/ingest/ContentBaseIngestHelper.java
  warehouse/query-core/src/test/java/datawave/mr/bulk/RecordIteratorTest.java
  warehouse/query-core/src/test/java/datawave/query/ancestor/AncestorChildExpansionIteratorTest.java
  warehouse/query-core/src/test/java/datawave/query/ancestor/AncestorUidIntersectorTest.java
Labels: enhancement, Integration Tested

#2120 re #2118: composite sequential execution mode
  web-services/common/src/main/java/datawave/webservice/common/remote/RemoteHttpService.java
  web-services/query/src/main/java/datawave/webservice/query/logic/composite/CompositeQueryConfiguration.java
  web-services/query/src/main/java/datawave/webservice/query/logic/composite/CompositeQueryLogic.java
  web-services/query/src/main/java/datawave/webservice/query/logic/composite/CompositeQueryLogicResults.java
  web-services/query/src/main/java/datawave/webservice/query/logic/composite/CompositeQueryLogicResultsIterator.java
  web-services/query/src/test/java/datawave/webservice/query/logic/composite/CompositeQueryLogicTest.java
Labels: Integration Tested, accepted

#1993 add the ability to use more precise field datatype regular expressions
  warehouse/ingest-core/src/main/java/datawave/ingest/data/config/ingest/BaseIngestHelper.java
  warehouse/ingest-core/src/test/java/datawave/ingest/data/config/XMLFieldConfigHelperTest.java
Labels: Integration Tested

#2006 Refactor data query expression filter constructors
  warehouse/query-core/src/main/java/datawave/query/ancestor/AncestorQueryIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/ParentQueryIterator.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/IteratorBuildingVisitor.java
  warehouse/query-core/src/main/java/datawave/query/predicate/AncestorEventDataFilter.java
  warehouse/query-core/src/main/java/datawave/query/predicate/EventDataQueryExpressionFilter.java
  warehouse/query-core/src/main/java/datawave/query/predicate/ParentEventDataFilter.java
  warehouse/query-core/src/main/java/datawave/query/predicate/TLDEventDataFilter.java
  warehouse/query-core/src/main/java/datawave/query/predicate/TermFrequencyDataFilter.java
  warehouse/query-core/src/main/java/datawave/query/tld/TLDQueryIterator.java
  warehouse/query-core/src/test/java/datawave/query/iterator/logic/TermFrequencyIndexIteratorTest.java
  warehouse/query-core/src/test/java/datawave/query/predicate/TLDEventDataFilterTest.java
  warehouse/query-core/src/test/java/datawave/query/predicate/TermFrequencyDataFilterTest.java
Labels: Integration Tested

#2147 Fixing the composite query logic to handle long running queries
  warehouse/query-core/src/main/java/datawave/query/transformer/GroupingTransform.java
  web-services/query/src/main/java/datawave/webservice/query/logic/composite/CompositeQueryConfiguration.java
  web-services/query/src/main/java/datawave/webservice/query/logic/composite/CompositeQueryLogic.java
  web-services/query/src/main/java/datawave/webservice/query/logic/composite/CompositeQueryLogicResults.java
  web-services/query/src/main/java/datawave/webservice/query/logic/composite/CompositeQueryLogicResultsIterator.java
  web-services/query/src/test/java/datawave/webservice/query/logic/composite/CompositeQueryLogicTest.java
Labels: Integration Tested

#2151 TLDEquality refactored to perform an in-line byte comparison
  warehouse/query-core/src/main/java/datawave/query/function/TLDEquality.java
  warehouse/query-core/src/test/java/datawave/query/function/TLDEqualityTest.java
Labels: Integration Tested
