Repository NationalSecurityAgency/datawave, pull requests merged in 2023-04, with the labels that each got.

#1922 Dynamically determine the default list of jexl functions
  warehouse/query-core/src/main/java/datawave/query/language/builder/jexl/JexlTreeBuilder.java
Labels: Integration Tested, accepted

#1921 Encapsulate field index aggregator within the QueryIterator stack
  warehouse/query-core/src/main/java/datawave/query/iterator/FieldIndexOnlyQueryIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/QueryOptions.java
  warehouse/query-core/src/main/java/datawave/query/iterator/facets/DynamicFacetIterator.java
  warehouse/query-core/src/main/java/datawave/query/tld/TLDQueryIterator.java
Labels: Integration Tested

#1926 Set data.name for JobSetupHandlers
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/IngestJob.java
Labels: Integration Tested

#1709 Ensure we dedup normalizers
  warehouse/query-core/src/main/java/datawave/query/jexl/nodes/BoundedRange.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ExpandMultiNormalizedTerms.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ExpandMultiNormalizedTermsTest.java
Labels: Integration Tested

#1847 Updated the geowave, geoutils, and geoserver versions to prevent some…
  pom.xml
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/GeoWaveFunctionsDescriptor.java
Labels: Integration Tested

#1838 Utility for generating test PKI materials for SSL testing
  contrib/datawave-test-pki/README.md
  contrib/datawave-test-pki/ca-config.json
  contrib/datawave-test-pki/ca-csr.json
  contrib/datawave-test-pki/client-csr.json
  contrib/datawave-test-pki/doit.sh
  contrib/datawave-test-pki/server-csr.json
Labels: Integration Tested

#1934 FunctionReferenceVisitor accepts optional namespace filter
  warehouse/query-core/src/main/java/datawave/query/jexl/JexlASTHelper.java
  warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/FunctionReferenceVisitor.java
  warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TermOffsetPopulator.java
  warehouse/query-core/src/test/java/datawave/query/postprocessing/tf/FunctionReferenceVisitorTest.java
Labels: Integration Tested

#1833 fixes #1832: Adds ability to get WKT for lat/lon geo functions.
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/GeoFunctionsDescriptor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/GeoFeatureVisitor.java
  warehouse/query-core/src/test/java/datawave/query/jexl/functions/GeoFunctionsDescriptorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/GeoFeatureVisitorTest.java
Labels: bug, Integration Tested

#1764 fixes #1763: Updates the QueryIterator to keep all valid ivarator cac…
  warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java
Labels: bug, Integration Tested

#1909 fixes #1834: Updated geometry/point normalizer to be able run concurr…
  pom.xml
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/GeoWaveFunctionsDescriptor.java
  warehouse/query-core/src/main/java/datawave/query/util/GeoWaveUtils.java
  warehouse/query-core/src/test/java/datawave/query/util/GeoWaveUtilsTest.java
Labels: bug, Integration Tested

#1902 Fix nested field group names, edge efficiencies
  warehouse/ingest-core/src/main/java/datawave/ingest/data/TypeRegistry.java
  warehouse/ingest-core/src/main/java/datawave/ingest/data/normalizer/SimpleGroupFieldNameParser.java
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/edge/ProtobufEdgeDataTypeHandler.java
  warehouse/ingest-core/src/test/java/datawave/ingest/data/normalizer/SimpleGroupFieldNameParserTest.java
  warehouse/ingest-core/src/test/java/datawave/ingest/mapreduce/handler/edge/ProtobufEdgeDeleteModeTest.java
  warehouse/ingest-core/src/test/resources/config/EdgeSpringConfig.xml
  warehouse/ingest-csv/src/main/java/datawave/ingest/csv/config/helper/ExtendedCSVIngestHelper.java
  warehouse/ingest-csv/src/test/resources/config/EdgeSpringConfig.xml
  warehouse/ingest-json/src/main/java/datawave/ingest/json/config/helper/JsonIngestHelper.java
  warehouse/ingest-json/src/test/resources/config/ingest/tvmaze-edge-definitions.xml
  warehouse/ingest-json/src/test/resources/config/ingest/tvmaze-ingest-config.xml
Labels: Integration Tested, accepted, linked
