Repository NationalSecurityAgency/datawave, pull requests merged in 2024-07, with the labels that each got.

#2434 Make #MATCHES_IN_GROUP work with a number
  pom.xml
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/GroupingRequiredFilterFunctions.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/GroupingRequiredFilterFunctionsDescriptor.java
  warehouse/query-core/src/test/java/datawave/query/NumericListQueryTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/functions/GroupingFiltersIngest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/functions/GroupingRequiredFilterFunctionsIntegrationTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/functions/GroupingRequiredFilterFunctionsTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ExpandMultiNormalizedTermsTest.java
Labels: Integration Tested

#2440 Fix ScoredPhrase Bug
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/ContentFunctionsDescriptor.java
  warehouse/query-core/src/test/java/datawave/query/jexl/functions/ContentFunctionsDescriptorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/FunctionIndexQueryExpansionVisitorTest.java
Labels: Integration Tested

#2425 Add option to sort query by field cardinality
  pom.xml
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryFieldsVisitor.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/test/java/datawave/query/ShapesTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryFieldsVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/util/ShapesIngest.java
Labels: Integration Tested

#2446 QueryFunctionsDescriptor returns all fields for multi-fielded functions
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/QueryFunctionsDescriptor.java
  warehouse/query-core/src/test/java/datawave/query/QueryFunctionQueryTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/functions/QueryFunctionsDescriptorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryOptionsFromQueryVisitorTest.java
Labels: Integration Tested

#2421 handle negated edge preconditions
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/edge/ProtobufEdgeDataTypeHandler.java
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/edge/evaluation/EdgeJexlInterpreter.java
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/edge/evaluation/EdgePreconditionArithmetic.java
  warehouse/ingest-core/src/test/java/datawave/ingest/mapreduce/handler/edge/ProtobufEdgePreconditionTest.java
  warehouse/ingest-core/src/test/resources/config/EdgeSpringConfigPrecon.xml
Labels: Integration Tested

#2470 Update for Sorting Query Terms
  warehouse/query-core/src/main/java/datawave/query/jexl/nodes/FieldOrTermNodeCostComparator.java
  warehouse/query-core/src/main/java/datawave/query/jexl/nodes/NodeCostComparator.java
  warehouse/query-core/src/test/java/datawave/query/TestLimitReturnedGroupsToHitTermGroups.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/order/OrderByCostVisitorTest.java
Labels: Integration Tested

#2356 Support for TableConfig changes
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/TableConfigurationUtil.java
  warehouse/ingest-core/src/main/java/datawave/ingest/table/config/AbstractTableConfigHelper.java
  warehouse/ingest-core/src/main/java/datawave/ingest/table/config/ShardTableConfigHelper.java
  warehouse/ingest-core/src/test/java/datawave/ingest/table/config/AbstractTableConfigHelperTest.java
Labels: linked

#2285 Correct DROP state for normalization bug.
  warehouse/ingest-core/src/main/java/datawave/ingest/data/config/ingest/BaseIngestHelper.java
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/shard/AbstractColumnBasedHandler.java
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/shard/ShardedDataTypeHandler.java
  warehouse/ingest-csv/src/test/java/datawave/ingest/csv/NormalizedContentInterfaceTest.java
  warehouse/ingest-csv/src/test/java/datawave/ingest/csv/ShardedDataTypeHandlerFailurePolicyTest.java
  warehouse/ingest-csv/src/test/resources/config/ingest/norm-content-interface.xml
  warehouse/ingest-csv/src/test/resources/input/my-nci.csv
Labels: bug, Integration Tested, linked
