Repository NationalSecurityAgency/datawave, pull requests merged in 2024-01, with the labels that each got.

#2207 Encapsulate Document Serialization in the QueryIterator
  warehouse/query-core/src/main/java/datawave/query/iterator/FieldIndexOnlyQueryIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/QueryOptions.java
  warehouse/query-core/src/main/java/datawave/query/iterator/ResultCountingIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/facets/DynamicFacetIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/profile/FinalDocumentTrackingIterator.java
Labels: Integration Tested

#2213 Significantly reduced the foot print of the xml field config helper by
  warehouse/ingest-core/src/main/java/datawave/ingest/data/config/XMLFieldConfigHelper.java
Labels: Integration Tested, accepted

#2214 Fix bypass accumulo option for accumulo2.1
  warehouse/core/src/main/java/datawave/mr/bulk/BulkIteratorEnvironment.java
  warehouse/query-core/src/main/java/datawave/mr/bulk/RecordIterator.java
  warehouse/query-core/src/main/java/datawave/query/tables/async/Scan.java
Labels: Integration Tested

#2221 Updated to choose best match for patterns in xml field config helper
  warehouse/ingest-core/src/main/java/datawave/ingest/data/config/XMLFieldConfigHelper.java
  warehouse/ingest-core/src/main/java/datawave/ingest/data/config/ingest/BaseIngestHelper.java
  warehouse/ingest-core/src/test/java/datawave/ingest/data/config/XMLFieldConfigHelperTest.java
Labels: Integration Tested, accepted

#2172 Adding ability to disable default props
  warehouse/ingest-core/src/main/java/datawave/ingest/TableCreator.java
  warehouse/ingest-core/src/main/java/datawave/ingest/table/config/AbstractTableConfigHelper.java
  warehouse/ingest-core/src/test/java/datawave/ingest/table/config/AbstractTableConfigHelperTest.java
Labels: Integration Tested

#2212 Improvements to BulkIngestMapFileLoader / BulkIngestMapFileLoaderTest…
  contrib/datawave-quickstart/bin/services/datawave/bootstrap-ingest.sh
  contrib/datawave-quickstart/bin/services/datawave/install-ingest.sh
  properties/dev.properties
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/BulkIngestMapFileLoader.java
  warehouse/ingest-core/src/test/java/datawave/ingest/mapreduce/job/BulkIngestMapFileLoaderTest.java
  warehouse/ingest-core/src/test/resources/datawave/rfiles/metadata/I3abcdef01.rf
  warehouse/ingest-core/src/test/resources/datawave/rfiles/shard/I2abcdef01.rf
  warehouse/ingest-scripts/src/main/resources/bin/ingest/start-loader.sh
Labels: Integration Tested, linked

#2199 Added config check CLI util
  microservices/configcheck/pom.xml
  microservices/configcheck/src/main/java/datawave/microservice/configcheck/Analysis.java
  microservices/configcheck/src/main/java/datawave/microservice/configcheck/AnalysisComparator.java
  microservices/configcheck/src/main/java/datawave/microservice/configcheck/CommandRunner.java
  microservices/configcheck/src/main/java/datawave/microservice/configcheck/ConfigCheckApplication.java
  microservices/configcheck/src/main/java/datawave/microservice/configcheck/Output.java
  microservices/configcheck/src/main/java/datawave/microservice/configcheck/XmlPropertyAnalyzer.java
  microservices/configcheck/src/main/java/datawave/microservice/configcheck/util/ArgumentUtils.java
  microservices/configcheck/src/main/java/datawave/microservice/configcheck/util/FileUtils.java
  microservices/configcheck/src/main/java/datawave/microservice/configcheck/util/XmlRenderUtils.java
  microservices/configcheck/src/main/resources/config/application.yml
  microservices/configcheck/src/main/resources/launch.conf
  microservices/configcheck/src/main/resources/log4j2.yml
  microservices/configcheck/src/test/java/datawave/microservice/configcheck/ConfigCheckApplicationTest.java
  microservices/configcheck/src/test/resources/input/microservice/QueryLogicFactory.xml
  microservices/configcheck/src/test/resources/input/microservice/yaml/application-query.yml
  microservices/configcheck/src/test/resources/input/webservice/QueryLogicFactory.xml
  microservices/configcheck/src/test/resources/input/webservice/properties/database.properties
  microservices/configcheck/src/test/resources/input/webservice/properties/default.properties
  microservices/configcheck/src/test/resources/rendered/comparison.diff
  microservices/configcheck/src/test/resources/rendered/fullComparison.diff
  microservices/configcheck/src/test/resources/rendered/microservice/QueryLogicFactory.xml
  microservices/configcheck/src/test/resources/rendered/microservice/analysis.txt
  microservices/configcheck/src/test/resources/rendered/microservice/fullReport.txt
  microservices/configcheck/src/test/resources/rendered/webservice/QueryLogicFactory.xml
  microservices/configcheck/src/test/resources/rendered/webservice/analysis.txt
  microservices/configcheck/src/test/resources/rendered/webservice/fullReport.txt
  microservices/pom.xml
Labels: Integration Tested

#2052 Updated AsyncIndexLookup to wait for timed out threads to finish befo…
  warehouse/query-core/src/main/java/datawave/query/jexl/lookups/AsyncIndexLookup.java
  warehouse/query-core/src/main/java/datawave/query/jexl/lookups/BoundedRangeIndexLookup.java
  warehouse/query-core/src/main/java/datawave/query/jexl/lookups/FieldNameIndexLookup.java
  warehouse/query-core/src/main/java/datawave/query/jexl/lookups/RegexIndexLookup.java
  warehouse/query-core/src/main/java/datawave/query/jexl/lookups/ShardIndexQueryTableStaticMethods.java
Labels: bug, Integration Tested

#2237 Enforce term threshold prior to range stream lookups
  warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
  warehouse/query-core/src/test/java/datawave/query/config/ShardQueryConfigurationTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ExecutableExpansionVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/planner/CompositeIndexTest.java
  warehouse/query-core/src/test/java/datawave/query/planner/GeoSortedQueryDataTest.java
  warehouse/query-core/src/test/resources/datawave/query/EventQueryLogicFactory.xml
  warehouse/query-core/src/test/resources/datawave/query/QueryLogicFactory.xml
Labels: Integration Tested

#2240 re #2239: clear the document before exiting the method.
  warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TermOffsetPopulator.java
  warehouse/query-core/src/test/java/datawave/query/postprocessing/tf/TermOffsetPopulatorTest.java
Labels: bug, Integration Tested
