Repository NationalSecurityAgency/datawave, pull requests merged in 2024-03, with the labels that each got.

#2293 fixes #2292: Continue looping when intermediate results are received
  web-services/query/src/main/java/datawave/webservice/query/logic/composite/CompositeQueryLogic.java
Labels: Integration Tested, accepted

#2142 re #2102: Added a #RENAME function, or query parameter rename.fields
  microservices/configcheck/src/test/resources/input/webservice/QueryLogicFactory.xml
  microservices/configcheck/src/test/resources/rendered/webservice/QueryLogicFactory.xml
  warehouse/query-core/src/main/java/datawave/query/QueryParameters.java
  warehouse/query-core/src/main/java/datawave/query/attributes/ExcerptFields.java
  warehouse/query-core/src/main/java/datawave/query/attributes/UniqueFields.java
  warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/QueryFunctions.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/QueryFunctionsDescriptor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryOptionsFromQueryVisitor.java
  warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/Rename.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/planner/QueryOptionsSwitch.java
  warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
  warehouse/query-core/src/main/java/datawave/query/transformer/DocumentTransformerSupport.java
  warehouse/query-core/src/main/java/datawave/query/transformer/FieldMappingTransform.java
  warehouse/query-core/src/main/java/datawave/query/transformer/FieldRenameTransform.java
  warehouse/query-core/src/test/java/datawave/query/config/ShardQueryConfigurationTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryOptionsFromQueryVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/transformer/FieldRenameTransformTest.java
  warehouse/query-core/src/test/resources/datawave/query/QueryLogicFactory.xml
  web-services/deploy/configuration/src/main/resources/datawave/query/QueryLogicFactory.xml
Labels: Integration Tested, accepted, linked

#2243 Refactor QueryPlan
  warehouse/query-core/src/main/java/datawave/query/index/lookup/RangeStream.java
  warehouse/query-core/src/main/java/datawave/query/index/lookup/ShardRangeStream.java
  warehouse/query-core/src/main/java/datawave/query/index/lookup/TupleToRange.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/planner/QueryPlan.java
  warehouse/query-core/src/main/java/datawave/query/scheduler/PushdownFunction.java
  warehouse/query-core/src/main/java/datawave/query/tables/facets/FacetQueryPlanVisitor.java
Labels: Integration Tested

#2219 Add Field and Term counts to serialized iterator options
  warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java
  warehouse/query-core/src/main/java/datawave/query/edge/DefaultExtendedEdgeQueryLogic.java
  warehouse/query-core/src/main/java/datawave/query/index/lookup/CreateUidsIterator.java
  warehouse/query-core/src/main/java/datawave/query/index/lookup/IndexInfo.java
  warehouse/query-core/src/main/java/datawave/query/index/lookup/RangeStream.java
  warehouse/query-core/src/main/java/datawave/query/index/lookup/ShardRangeStream.java
  warehouse/query-core/src/main/java/datawave/query/index/lookup/TupleToRange.java
  warehouse/query-core/src/main/java/datawave/query/iterator/QueryOptions.java
  warehouse/query-core/src/main/java/datawave/query/planner/BooleanChunkingQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/planner/FacetedQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/planner/IndexQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/planner/QueryPlan.java
  warehouse/query-core/src/main/java/datawave/query/planner/ThreadedRangeBundlerIterator.java
  warehouse/query-core/src/main/java/datawave/query/scheduler/PushdownFunction.java
  warehouse/query-core/src/main/java/datawave/query/scheduler/SequentialScheduler.java
  warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
  warehouse/query-core/src/main/java/datawave/query/tables/edge/EdgeQueryLogic.java
  warehouse/query-core/src/main/java/datawave/query/tables/facets/FacetQueryPlanVisitor.java
  warehouse/query-core/src/test/java/datawave/query/config/ShardQueryConfigurationTest.java
  warehouse/query-core/src/test/java/datawave/query/index/lookup/CreateUidsIteratorTest.java
  warehouse/query-core/src/test/java/datawave/query/index/lookup/IndexInfoTest.java
  warehouse/query-core/src/test/java/datawave/query/iterator/QueryOptionsTest.java
  warehouse/query-core/src/test/resources/datawave/query/QueryLogicFactory.xml
  web-services/query/src/main/java/datawave/webservice/query/configuration/QueryData.java
  web-services/query/src/test/java/datawave/webservice/query/configuration/QueryDataTest.java
Labels: Integration Tested

#2310 fixes #2309: Do not reach out to remote user operations when asked
  web-services/query/src/main/java/datawave/webservice/query/runner/RunningQuery.java
  web-services/query/src/main/java/datawave/webservice/query/util/LookupUUIDUtil.java
  web-services/query/src/test/java/datawave/webservice/query/runner/ExtendedQueryExecutorBeanTest.java
  web-services/security/src/main/java/datawave/security/authorization/remote/RemoteUserOperationsImpl.java
Labels: Integration Tested

#2242 Implements the chained SSDeep Discovery Query
  warehouse/assemble/datawave/pom.xml
  warehouse/ingest-scripts/src/main/resources/bin/ingest/findJars.sh
  warehouse/ingest-scripts/src/main/resources/bin/ingest/ingest-libs.sh
  warehouse/query-core/src/main/java/datawave/query/tables/ssdeep/DiscoveredSSDeep.java
  warehouse/query-core/src/main/java/datawave/query/tables/ssdeep/FullSSDeepDiscoveryChainStrategy.java
  warehouse/query-core/src/main/java/datawave/query/tables/ssdeep/SSDeepChainedDiscoveryQueryLogic.java
  warehouse/query-core/src/main/java/datawave/query/tables/ssdeep/SSDeepDiscoveryQueryLogic.java
  warehouse/query-core/src/main/java/datawave/query/tables/ssdeep/SSDeepScoringFunction.java
  warehouse/query-core/src/main/java/datawave/query/tables/ssdeep/SSDeepSimilarityQueryTransformer.java
  warehouse/query-core/src/test/java/datawave/query/tables/ssdeep/SSDeepIndexQueryTest.java
  warehouse/query-core/src/test/java/datawave/query/tables/ssdeep/SSDeepIngestQueryTest.java
  warehouse/query-core/src/test/java/datawave/query/tables/ssdeep/SSDeepSimilarityQueryTest.java
  web-services/deploy/configuration/src/main/resources/datawave/query/SSDeepQueryLogicFactory.xml
Labels: Integration Tested

#1800 1797 - Fix the Blocker level issues found by SonarQube
  warehouse/core/src/main/java/datawave/iterators/filter/ConfigurableAgeOffFilter.java
  warehouse/ingest-core/src/main/java/datawave/ingest/data/TypeRegistry.java
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/BulkIngestMapFileLoader.java
  warehouse/ingest-core/src/main/java/datawave/ingest/time/Now.java
  warehouse/ingest-core/src/main/java/datawave/ingest/util/NGramTokenizationStrategy.java
  warehouse/metrics-core/src/main/java/datawave/metrics/analytic/FileByteSummaryLoader.java
  warehouse/query-core/src/main/java/datawave/query/index/lookup/ShardRangeStream.java
  warehouse/query-core/src/main/java/datawave/query/index/stats/IndexStatsClient.java
  warehouse/query-core/src/main/java/datawave/query/jexl/lookups/ShardIndexQueryTableStaticMethods.java
  warehouse/query-core/src/main/java/datawave/query/scheduler/PushdownFunction.java
  warehouse/query-core/src/main/java/datawave/query/statsd/QueryStatsDClient.java
  warehouse/query-core/src/main/java/datawave/query/tracking/ActiveQueryLog.java
  web-services/security/src/main/java/datawave/security/cache/AccumuloCacheStore.java
Labels: Integration Tested

#2287 Adding before/after parameters to hit callout for excerpt fields function
  warehouse/query-core/src/main/java/datawave/query/attributes/ExcerptFields.java
  warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/ExcerptFields.java
  warehouse/query-core/src/main/java/datawave/query/transformer/ExcerptTransform.java
  warehouse/query-core/src/test/java/datawave/query/ExcerptTest.java
  warehouse/query-core/src/test/java/datawave/query/attributes/ExcerptFieldsTest.java
Labels: Integration Tested

#2311 IngestTypePruningVisitor correctly handles null literals
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/IngestTypePruningVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/IngestTypeVisitor.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/IngestTypePruningVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/IngestTypeVisitorTest.java
Labels: Integration Tested

#2306 Ordering Visitor
  warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java
  warehouse/query-core/src/main/java/datawave/query/index/lookup/CreateUidsIterator.java
  warehouse/query-core/src/main/java/datawave/query/index/lookup/IndexInfo.java
  warehouse/query-core/src/main/java/datawave/query/index/lookup/RangeStream.java
  warehouse/query-core/src/main/java/datawave/query/iterator/QueryOptions.java
  warehouse/query-core/src/main/java/datawave/query/jexl/nodes/DefaultNodeCostComparator.java
  warehouse/query-core/src/main/java/datawave/query/jexl/nodes/FieldOrTermNodeCostComparator.java
  warehouse/query-core/src/main/java/datawave/query/jexl/nodes/NodeCostComparator.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/order/OrderByCostVisitor.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/planner/QueryPlan.java
  warehouse/query-core/src/main/java/datawave/query/planner/ThreadedRangeBundlerIterator.java
  warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
  warehouse/query-core/src/main/java/datawave/query/util/count/CountMap.java
  warehouse/query-core/src/main/java/datawave/query/util/count/CountMapSerDe.java
  warehouse/query-core/src/main/java/org/apache/commons/jexl3/parser/JexlNodes.java
  warehouse/query-core/src/test/java/datawave/query/config/ShardQueryConfigurationTest.java
  warehouse/query-core/src/test/java/datawave/query/index/lookup/CreateUidsIteratorTest.java
  warehouse/query-core/src/test/java/datawave/query/index/lookup/IndexInfoTest.java
  warehouse/query-core/src/test/java/datawave/query/iterator/QueryOptionsTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/nodes/DefaultNodeCostComparatorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/order/OrderByCostVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/tables/RemoteEventQueryLogicTest.java
  warehouse/query-core/src/test/java/datawave/query/util/count/CountMapSerDeTest.java
  warehouse/query-core/src/test/resources/datawave/query/QueryLogicFactory.xml
Labels: Integration Tested

#2313 handle evalOnly and delayed regular expressions for non-indexOnly non…
  contrib/datawave-quickstart/bin/services/datawave/test-web/responses/EventQueryJexlSyntax.test/JexlWildFieldedPage1.expected
  contrib/datawave-quickstart/bin/services/datawave/test-web/tests/EventQueryJexlSyntax.test
  warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/DelayedNonEventSubTreeVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ExecutableDeterminationVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/IteratorBuildingVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/IvaratorRequiredVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/LiteralNodeSubsetVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/RegexIndexExpansionVisitor.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TermOffsetPopulator.java
  warehouse/query-core/src/test/java/datawave/query/NumericListQueryTest.java
  warehouse/query-core/src/test/java/datawave/query/RegexQueryTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ExecutableDeterminationVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/tables/ShardQueryLogicTest.java
  warehouse/query-core/src/test/java/datawave/query/testframework/AbstractDataTypeConfig.java
  warehouse/query-core/src/test/java/datawave/query/testframework/AbstractFields.java
  warehouse/query-core/src/test/java/datawave/query/testframework/FieldConfig.java
  warehouse/query-core/src/test/java/datawave/query/testframework/cardata/AbstractCarFields.java
Labels: Integration Tested
