Repository NationalSecurityAgency/datawave, pull requests merged in 2024-02, with the labels that each got.

#2255 Use thread safe date package
  pom.xml
Labels: Integration Tested, linked

#2273 Do not reduce fields when preloading iterator options
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
Labels: bug, Integration Tested

#2093 Updates to try and avoid hanging ivarators
  properties/default.properties
  warehouse/query-core/src/main/java/datawave/core/iterators/DatawaveFieldIndexCachingIteratorJexl.java
  warehouse/query-core/src/main/java/datawave/core/iterators/IteratorThreadPoolManager.java
  warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java
  warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/QueryOptions.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
  warehouse/query-core/src/test/java/datawave/query/config/ShardQueryConfigurationTest.java
  web-services/deploy/configuration/src/main/resources/datawave/query/QueryLogicFactory.xml
Labels: Integration Tested, accepted

#2200 Use the pluginEnvironment instead of AccumuloConfiguration as the
  warehouse/query-core/src/main/java/datawave/core/iterators/IteratorThreadPoolManager.java
  warehouse/query-core/src/test/java/datawave/query/iterator/QueryIteratorIT.java
  warehouse/query-core/src/test/java/datawave/query/iterator/SourceManagerTest.java
Labels: Integration Tested, accepted

#2094 Enrich 'i' and 'ri' rows in metadata table with event date
  warehouse/ingest-core/src/main/java/datawave/ingest/metadata/EventMetadata.java
  warehouse/ingest-core/src/main/java/datawave/ingest/metadata/MetadataCounterGroup.java
  warehouse/ingest-core/src/main/java/datawave/ingest/metadata/MetadataWithEventDate.java
  warehouse/ingest-core/src/main/java/datawave/ingest/metadata/MetadataWithMostRecentDate.java
  warehouse/ingest-core/src/main/java/datawave/ingest/table/config/MetadataTableConfigHelper.java
  warehouse/ingest-core/src/test/java/datawave/TestBaseIngestHelper.java
  warehouse/ingest-core/src/test/java/datawave/ingest/metadata/EventMetadataTest.java
  warehouse/ingest-core/src/test/java/datawave/ingest/metadata/MetadataCounterGroupTest.java
  warehouse/ingest-core/src/test/java/datawave/ingest/metadata/MetadataWithMostRecentDateTest.java
  warehouse/ingest-csv/src/test/java/datawave/ingest/csv/TableConfigurationUtilTest.java
Labels: Integration Tested, accepted, linked

#2176 2170 - update dependencies
  pom.xml
  warehouse/pom.xml
  web-services/client/pom.xml
  web-services/map-reduce/pom.xml
  web-services/pom.xml
Labels: Integration Tested

#2165 2013 - jexl uuid query parser research/changes
  warehouse/query-core/src/main/java/datawave/query/language/parser/jexl/LuceneToJexlUUIDQueryParser.java
  warehouse/query-core/src/main/java/datawave/query/language/parser/lucene/LuceneQueryParser.java
Labels: Integration Tested

#2254 Optionally limit query execution by indexed terms
  warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/IndexedTermCountingVisitor.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
  warehouse/query-core/src/test/java/datawave/query/config/ShardQueryConfigurationTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ExecutableExpansionVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/IndexedTermCountingVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/planner/CompositeIndexTest.java
  warehouse/query-core/src/test/java/datawave/query/planner/GeoSortedQueryDataTest.java
  warehouse/query-core/src/test/resources/datawave/query/EventQueryLogicFactory.xml
  warehouse/query-core/src/test/resources/datawave/query/QueryLogicFactory.xml
Labels: Integration Tested

#2271 Feature/ingest filter
  contrib/datawave-quickstart/bin/services/datawave/bootstrap.sh
  properties/dev.properties
  warehouse/ingest-configuration/src/main/resources/config/ingest-config.xml
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/DataTypeDiscardFutureIntervalPredicate.java
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/DataTypeDiscardIntervalPredicate.java
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/EventMapper.java
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/RawRecordPredicate.java
  warehouse/ingest-core/src/main/java/datawave/ingest/metric/IngestInput.java
  warehouse/ingest-core/src/test/java/datawave/ingest/mapreduce/EventMapperTest.java
  warehouse/query-core/src/test/java/datawave/query/testframework/HadoopTestConfiguration.java
Labels: Integration Tested, accepted, linked

#2257 Fix AddDateFilter to produce a flattened query tree
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
Labels: Integration Tested

#2140 re #707: Updated to make use of intermediate results for the Unique
  warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java
  warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
  warehouse/query-core/src/main/java/datawave/query/transformer/UniqueTransform.java
  warehouse/query-core/src/test/java/datawave/query/LongRunningQueryTest.java
  warehouse/query-core/src/test/java/datawave/query/UniqueTest.java
  warehouse/query-core/src/test/java/datawave/query/transformer/UniqueTransformTest.java
  warehouse/query-core/src/test/java/datawave/query/util/VisibilityWiseGuysIngest.java
Labels: Integration Tested, accepted

#2220 re #2104: ivarator limit
  warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java
  warehouse/query-core/src/main/java/datawave/query/jexl/NodeTypeCount.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/NodeTypeCountVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPropertyMarkerVisitor.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
  warehouse/query-core/src/main/java/datawave/query/tables/async/event/VisitorFunction.java
  warehouse/query-core/src/main/java/org/apache/commons/jexl3/parser/RandomTreeBuilder.java
  warehouse/query-core/src/test/java/datawave/query/config/ShardQueryConfigurationTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/NodeTypeCountVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/tables/async/event/VisitorFunctionTest.java
Labels: Integration Tested, accepted, linked

#2252 Fixes QEB's max results override validation (#2251)
  web-services/query/src/main/java/datawave/webservice/query/runner/QueryExecutorBean.java
  web-services/query/src/test/java/datawave/webservice/query/runner/ExtendedQueryExecutorBeanTest.java
  web-services/query/src/test/java/datawave/webservice/query/runner/QueryExecutorBeanTest.java
Labels: bug, linked

#2089 2080 - fix sonarqube security hotspots
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/summary/util/MetricRuleUtil.java
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/IngestJob.java
  warehouse/query-core/src/main/java/datawave/core/iterators/DatawaveFieldIndexCachingIteratorJexl.java
  warehouse/query-core/src/main/java/datawave/query/tables/async/event/VisitorFunction.java
  web-services/cached-results/src/main/java/datawave/webservice/query/database/CachedResultsCleanupBean.java
  web-services/cached-results/src/main/java/datawave/webservice/results/cached/CachedResultsBean.java
  web-services/cached-results/src/main/java/datawave/webservice/results/cached/CachedRunningQuery.java
  web-services/security/src/main/java/datawave/security/authorization/simple/DatabaseUserService.java
Labels: Integration Tested

#2217 Updating excerpt callout based on added testing
  warehouse/query-core/src/main/java/datawave/query/transformer/ExcerptTransform.java
  warehouse/query-core/src/test/java/datawave/query/ExcerptTest.java
  warehouse/query-core/src/test/java/datawave/query/transformer/ExcerptTransformTest.java
  warehouse/query-core/src/test/java/datawave/query/util/WiseGuysIngest.java
Labels: Integration Tested

#2284 Add Option to Reduce Datatype Filter
  warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java
  warehouse/query-core/src/main/java/datawave/query/index/lookup/RangeStream.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/IngestTypePruningVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/IngestTypeVisitor.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
  warehouse/query-core/src/main/java/datawave/query/tables/async/event/VisitorFunction.java
  warehouse/query-core/src/test/java/datawave/query/config/ShardQueryConfigurationTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/IngestTypePruningVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/IngestTypeVisitorTest.java
  warehouse/query-core/src/test/resources/datawave/query/QueryLogicFactory.xml
Labels: Integration Tested
