Repository NationalSecurityAgency/datawave, pull requests merged in 2025-02, with the labels that each got.

#2725 Protect against concurrent mod exceptions when processing moves for a
  warehouse/query-core/src/main/java/datawave/query/iterator/logic/NestedIteratorContextUtil.java
  warehouse/query-core/src/test/java/datawave/query/ShapesTest.java
Labels: Integration Tested

#2712 Refactor build document logic
  warehouse/query-core/src/main/java/datawave/query/iterator/builder/AbstractIteratorBuilder.java
  warehouse/query-core/src/main/java/datawave/query/iterator/builder/CardinalityIteratorBuilder.java
  warehouse/query-core/src/main/java/datawave/query/iterator/builder/IndexIteratorBuilder.java
  warehouse/query-core/src/main/java/datawave/query/iterator/builder/IndexListIteratorBuilder.java
  warehouse/query-core/src/main/java/datawave/query/iterator/builder/IndexRangeIteratorBuilder.java
  warehouse/query-core/src/main/java/datawave/query/iterator/builder/IndexRegexIteratorBuilder.java
  warehouse/query-core/src/main/java/datawave/query/iterator/facets/DynamicFacetIterator.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/IteratorBuildingVisitor.java
  warehouse/query-core/src/main/java/datawave/query/tables/facets/FacetedQueryLogic.java
  warehouse/query-core/src/main/java/datawave/query/tld/TLDIndexBuildingVisitor.java
  warehouse/query-core/src/main/java/datawave/query/tld/TLDIndexIteratorBuilder.java
  warehouse/query-core/src/test/java/datawave/query/tables/facets/FacetedQueryLogicTest.java
Labels: Integration Tested

#2732 Remove tablet locator bin ranges
  warehouse/query-core/src/main/java/datawave/query/scheduler/PushdownFunction.java
  warehouse/query-core/src/main/java/datawave/query/scheduler/PushdownScheduler.java
  warehouse/query-core/src/main/java/datawave/query/tables/BatchScannerSession.java
  warehouse/query-core/src/test/java/datawave/query/MixedGeoAndGeoWaveTest.java
Labels: Integration Tested

#2726 SatisfactionVisitor now considers bounded ranges to be satisfiable
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/IteratorBuildingVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/SatisfactionVisitor.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/IteratorBuildingVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/SatisfactionVisitorTest.java
Labels: Integration Tested

#2744 Updated the composite query logic to handle the validateQuery mechanism
  core/query/src/main/java/datawave/core/query/logic/DelegatingQueryLogic.java
  core/query/src/main/java/datawave/core/query/logic/composite/CompositeQueryLogic.java
  core/query/src/main/java/datawave/core/query/logic/filtered/FilteredQueryLogic.java
  web-services/query/src/test/java/datawave/webservice/query/logic/composite/CompositeQueryLogicTest.java
Labels: Integration Tested, accepted

#2743 Hint to Shards Iterator
  warehouse/query-core/src/main/java/datawave/query/index/lookup/HintToShardIterator.java
  warehouse/query-core/src/main/java/datawave/query/index/lookup/RangeStream.java
  warehouse/query-core/src/test/java/datawave/query/index/lookup/HintToShardIteratorTest.java
Labels: Integration Tested

#2717 Redesign of the DatePartitionedQueryPlanner (formerly know as the FederatedQueryPlanner)
  core/utils/metadata-utils/.gitrepo
  core/utils/metadata-utils/pom.xml
  core/utils/metadata-utils/src/main/java/datawave/query/model/IndexFieldHole.java
  core/utils/metadata-utils/src/main/java/datawave/query/util/AllFieldMetadataHelper.java
  core/utils/metadata-utils/src/main/java/datawave/query/util/MetadataHelper.java
  core/utils/metadata-utils/src/test/java/datawave/query/model/IndexFieldHoleTest.java
  core/utils/metadata-utils/src/test/java/datawave/query/util/AllFieldMetadataHelperTest.java
  pom.xml
  warehouse/query-core/src/main/java/datawave/query/config/IndexHole.java
  warehouse/query-core/src/main/java/datawave/query/config/IndexValueHole.java
  warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java
  warehouse/query-core/src/main/java/datawave/query/jexl/nodes/QueryPropertyMarker.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/JexlStringBuildingVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/PushdownMissingIndexRangeNodesVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/PushdownUnindexedFieldsVisitor.java
  warehouse/query-core/src/main/java/datawave/query/planner/DatePartitionedQueryIterable.java
  warehouse/query-core/src/main/java/datawave/query/planner/DatePartitionedQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/planner/FederatedQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/tables/AncestorQueryLogic.java
  warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
  warehouse/query-core/src/test/java/datawave/query/AnyFieldQueryTest.java
  warehouse/query-core/src/test/java/datawave/query/CompositeFunctionsTest.java
  warehouse/query-core/src/test/java/datawave/query/DelayedIndexOnlyQueryTest.java
  warehouse/query-core/src/test/java/datawave/query/IndexValueHoleQueryTest.java
  warehouse/query-core/src/test/java/datawave/query/MaxExpansionIndexOnlyQueryTest.java
  warehouse/query-core/src/test/java/datawave/query/PushdownQueryTest.java
  warehouse/query-core/src/test/java/datawave/query/QueryPlanTest.java
  warehouse/query-core/src/test/java/datawave/query/RangeQueryTest.java
  warehouse/query-core/src/test/java/datawave/query/TextFunctionQueryTest.java
  warehouse/query-core/src/test/java/datawave/query/config/ShardQueryConfigurationTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/PushdownMissingIndexRangeNodesVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/PushdownUnindexedFieldsVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/planner/DatePartitionedQueryPlannerTest.java
  warehouse/query-core/src/test/java/datawave/query/planner/FederatedQueryTest.java
  warehouse/query-core/src/test/java/datawave/query/planner/PartitionedPlanVisitor.java
  warehouse/query-core/src/test/java/datawave/query/tables/IndexQueryLogicTest.java
  warehouse/query-core/src/test/java/datawave/query/testframework/AbstractFunctionalQuery.java
  warehouse/query-core/src/test/java/datawave/query/util/FieldIndexHoleDataIngest.java
  warehouse/query-core/src/test/java/datawave/query/util/IndexFieldHoleDataIngest.java
  warehouse/query-core/src/test/java/datawave/query/util/MockMetadataHelper.java
  warehouse/query-core/src/test/java/datawave/query/util/WiseGuysIngest.java
Labels: Integration Tested, linked
