Repository NationalSecurityAgency/datawave, pull requests merged in 2025-01, with the labels that each got.

#2630 Removing unused reduced response from various Attribute methods
  warehouse/query-core/src/main/java/datawave/query/attributes/Attribute.java
  warehouse/query-core/src/main/java/datawave/query/attributes/Attributes.java
  warehouse/query-core/src/main/java/datawave/query/attributes/Cardinality.java
  warehouse/query-core/src/main/java/datawave/query/attributes/Content.java
  warehouse/query-core/src/main/java/datawave/query/attributes/DateContent.java
  warehouse/query-core/src/main/java/datawave/query/attributes/DiacriticContent.java
  warehouse/query-core/src/main/java/datawave/query/attributes/Document.java
  warehouse/query-core/src/main/java/datawave/query/attributes/DocumentKey.java
  warehouse/query-core/src/main/java/datawave/query/attributes/GeoPoint.java
  warehouse/query-core/src/main/java/datawave/query/attributes/Geometry.java
  warehouse/query-core/src/main/java/datawave/query/attributes/IpAddress.java
  warehouse/query-core/src/main/java/datawave/query/attributes/Latitude.java
  warehouse/query-core/src/main/java/datawave/query/attributes/Longitude.java
  warehouse/query-core/src/main/java/datawave/query/attributes/Numeric.java
  warehouse/query-core/src/main/java/datawave/query/attributes/PreNormalizedAttribute.java
  warehouse/query-core/src/main/java/datawave/query/attributes/TypeAttribute.java
  warehouse/query-core/src/main/java/datawave/query/function/DataTypeAsField.java
  warehouse/query-core/src/main/java/datawave/query/function/DocumentProjection.java
  warehouse/query-core/src/main/java/datawave/query/function/FacetedGrouping.java
  warehouse/query-core/src/main/java/datawave/query/function/GroupFields.java
  warehouse/query-core/src/main/java/datawave/query/function/KryoCVAwareSerializableSerializer.java
  warehouse/query-core/src/main/java/datawave/query/function/LimitFields.java
  warehouse/query-core/src/main/java/datawave/query/function/RemoveGroupingContext.java
  warehouse/query-core/src/main/java/datawave/query/function/serializer/WritableDocumentSerializer.java
  warehouse/query-core/src/main/java/datawave/query/iterator/GroupingIterator.java
  warehouse/query-core/src/main/java/datawave/query/transformer/ContentTransform.java
  warehouse/query-core/src/main/java/datawave/query/transformer/FieldMappingTransform.java
  warehouse/query-core/src/main/java/datawave/query/transformer/FieldRenameTransform.java
  warehouse/query-core/src/test/java/datawave/query/common/grouping/DocumentGrouperTest.java
  warehouse/query-core/src/test/java/datawave/query/transformer/FieldRenameTransformTest.java
  warehouse/query-core/src/test/java/datawave/query/transformer/UniqueTransformTest.java
Labels: linked

#2681 Store active job cache pointer in Zookeeper
  properties/default.properties
  warehouse/ingest-core/pom.xml
  warehouse/ingest-core/src/main/java/datawave/ingest/jobcache/ActiveSetter.java
  warehouse/ingest-core/src/main/java/datawave/ingest/jobcache/NonEmptyStringValidator.java
  warehouse/ingest-core/src/main/java/datawave/ingest/jobcache/SetActiveCommand.java
  warehouse/ingest-core/src/test/java/datawave/ingest/jobcache/ActiveSetterTest.java
  warehouse/ingest-scripts/src/main/resources/bin/ingest/findJars.sh
  warehouse/ingest-scripts/src/main/resources/bin/ingest/ingest-env.sh
  warehouse/ingest-scripts/src/main/resources/bin/ingest/ingest-libs.sh
  warehouse/ingest-scripts/src/main/resources/bin/ingest/load-job-cache.sh
Labels: Integration Tested

#2662 Add ability to configure date types for no expansion
  warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
  warehouse/query-core/src/test/java/datawave/query/config/ShardQueryConfigurationTest.java
  warehouse/query-core/src/test/java/datawave/query/planner/DefaultQueryPlannerTest.java
Labels: Integration Tested, linked

#2686 Prevent the IteratorBuildingVisitor from making unnecessary copies
  warehouse/query-core/src/main/java/datawave/query/ancestor/AncestorIndexBuildingVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/IteratorBuildingVisitor.java
  warehouse/query-core/src/main/java/datawave/query/tld/TLDIndexBuildingVisitor.java
  warehouse/query-core/src/test/java/datawave/query/iterator/QueryIteratorIT.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/IteratorBuildingVisitorTest.java
Labels: Integration Tested

#2684 NestedIterator provides native support for a seek method
  warehouse/query-core/src/main/java/datawave/query/iterator/AccumuloTreeIterable.java
  warehouse/query-core/src/main/java/datawave/query/iterator/EmptyTreeIterable.java
  warehouse/query-core/src/main/java/datawave/query/iterator/EventDataScanNestedIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/EventFieldIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/NestedIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/NestedQueryIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/SeekableIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/SeekableNestedIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/logic/AndIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/logic/ArrayIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/logic/IndexIteratorBridge.java
  warehouse/query-core/src/main/java/datawave/query/iterator/logic/OrIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/logic/RangeFilterIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/logic/RegexFilterIterator.java
  warehouse/query-core/src/main/java/datawave/query/jexl/DelayedNonEventIndexContext.java
  warehouse/query-core/src/test/java/datawave/query/iterator/NestedQueryIteratorTest.java
  warehouse/query-core/src/test/java/datawave/query/iterator/logic/AndOrIteratorIT.java
  warehouse/query-core/src/test/java/datawave/query/iterator/logic/IndexIteratorBridgeTest.java
  warehouse/query-core/src/test/java/datawave/query/iterator/logic/NegationFilterTest.java
  warehouse/query-core/src/test/java/datawave/query/iterator/logic/OrIteratorIT.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/IteratorBuildingVisitorTest.java
Labels: Integration Tested

#2660 Add FieldExpansionIterator that replaces the ANYFIELD scanner
  warehouse/query-core/src/main/java/datawave/core/iterators/FieldExpansionIterator.java
  warehouse/query-core/src/main/java/datawave/query/data/parsers/ShardIndexKey.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/QueryFunctionsDescriptor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/lookups/AsyncIndexLookup.java
  warehouse/query-core/src/main/java/datawave/query/jexl/lookups/BoundedRangeIndexLookup.java
  warehouse/query-core/src/main/java/datawave/query/jexl/lookups/FieldExpansionIndexLookup.java
  warehouse/query-core/src/main/java/datawave/query/jexl/lookups/FieldNameIndexLookup.java
  warehouse/query-core/src/main/java/datawave/query/jexl/lookups/IndexLookupMap.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ExpandMultiNormalizedTerms.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/UnfieldedIndexExpansionVisitor.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/tables/async/event/VisitorFunction.java
  warehouse/query-core/src/test/java/datawave/core/iterators/FieldExpansionIteratorTest.java
  warehouse/query-core/src/test/java/datawave/query/AnyFieldQueryTest.java
  warehouse/query-core/src/test/java/datawave/query/TextFunctionQueryTest.java
  warehouse/query-core/src/test/java/datawave/query/UnindexedNumericQueryTest.java
  warehouse/query-core/src/test/java/datawave/query/data/parsers/ShardIndexKeyTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/functions/QueryFunctionsDescriptorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ExpandMultiNormalizedTermsTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/UnfieldedIndexExpansionVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/language/parser/jexl/TestLuceneToJexlQueryParser.java
Labels: Integration Tested

#2670 Updating jackson version in pom
  pom.xml
Labels: Integration Tested

#2709 Updated the GlobalIndexUidAggregator to truncate timestamps on keys
  warehouse/core/src/main/java/datawave/util/CompositeTimestamp.java
  warehouse/core/src/test/java/datawave/util/CompositeTimestampTest.java
  warehouse/ingest-core/src/main/java/datawave/ingest/table/aggregator/GlobalIndexUidAggregator.java
  warehouse/ingest-core/src/main/java/datawave/ingest/table/aggregator/TruncatingTimestampIterator.java
  warehouse/ingest-core/src/main/java/datawave/iterators/TotalAggregatingIterator.java
  warehouse/ingest-core/src/test/java/datawave/ingest/table/aggregator/AggregatorIntegrationTests.java
  warehouse/ingest-core/src/test/java/datawave/ingest/table/aggregator/GlobalIndexUidAggregatorTest.java
  warehouse/ingest-core/src/test/java/datawave/ingest/table/aggregator/TruncatingTimestampIteratorTest.java
  warehouse/query-core/src/main/java/datawave/query/index/lookup/CreateUidsIterator.java
  warehouse/query-core/src/test/java/datawave/query/util/WiseGuysIngest.java
Labels: Integration Tested

#2694 improve query iterator source management
  warehouse/query-core/src/main/java/datawave/query/iterator/ParentQueryIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/SourceFactory.java
  warehouse/query-core/src/main/java/datawave/query/iterator/pipeline/Pipeline.java
  warehouse/query-core/src/main/java/datawave/query/iterator/pipeline/PipelinePool.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/IteratorBuildingVisitor.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/IteratorBuildingVisitorTest.java
Labels: Integration Tested, linked

#2510 Throw a QueryException when an error occurs when parsing JEXL syntax
  warehouse/query-core/src/main/java/datawave/query/jexl/JexlASTHelper.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/ContentFunctionsDescriptor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctions.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctionsDescriptor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/GeoFunctions.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/GeoFunctionsDescriptor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/GeoWaveFunctions.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/GeoWaveFunctionsDescriptor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/GroupingRequiredFilterFunctionsDescriptor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/JexlFunctionArgumentDescriptorFactory.java
  warehouse/query-core/src/main/java/datawave/query/jexl/functions/QueryFunctionsDescriptor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/lookups/ShardIndexQueryTableStaticMethods.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/EdgeTableRangeBuildingVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/FixNegativeNumbersVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/JexlStringBuildingVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/PrintingVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/VariableNameVisitor.java
  warehouse/query-core/src/test/java/datawave/query/jexl/JexlASTHelperTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctionsTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/FieldToFieldComparisonVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ValidComparisonVisitorTest.java
Labels: Integration Tested

#2713 Expand test cases for the SatisfactionVisitor.
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/IteratorBuildingVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/SatisfactionVisitor.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/SatisfactionVisitorTest.java
Labels: Integration Tested
