Repository NationalSecurityAgency/datawave, pull requests merged in 2025-06, with the labels that each got.

#2937 Implements visibility marking merging for tag clouds
  warehouse/keyword-common/src/main/java/datawave/util/keyword/DefaultTagCloudUtils.java
  warehouse/keyword-common/src/main/java/datawave/util/keyword/KeywordExtractor.java
  warehouse/keyword-common/src/main/java/datawave/util/keyword/KeywordResults.java
  warehouse/keyword-common/src/main/java/datawave/util/keyword/TagCloud.java
  warehouse/keyword-common/src/main/java/datawave/util/keyword/TagCloudEntry.java
  warehouse/keyword-common/src/main/java/datawave/util/keyword/TagCloudUtils.java
  warehouse/keyword-common/src/main/java/datawave/util/keyword/VisibleContent.java
  warehouse/keyword-common/src/test/java/datawave/util/keyword/KeywordResultsTest.java
  warehouse/keyword-common/src/test/java/datawave/util/keyword/TagCloudTest.java
  warehouse/query-core/src/main/java/datawave/query/config/KeywordQueryConfiguration.java
  warehouse/query-core/src/main/java/datawave/query/iterator/logic/KeywordExtractingIterator.java
  warehouse/query-core/src/main/java/datawave/query/tables/keyword/KeywordQueryLogic.java
  warehouse/query-core/src/main/java/datawave/query/tables/keyword/KeywordQueryState.java
  warehouse/query-core/src/main/java/datawave/query/transformer/TagCloudTransformer.java
  warehouse/query-core/src/test/java/datawave/query/tables/keyword/KeywordQueryLogicFunctionalTest.java
  warehouse/query-core/src/test/java/datawave/query/tables/keyword/KeywordQueryLogicTest.java
  warehouse/query-core/src/test/java/datawave/query/tables/keyword/KeywordUUIDChainStrategyTest.java
  warehouse/query-core/src/test/java/datawave/query/tables/keyword/TagCloudTransformerTest.java
  web-services/deploy/configuration/src/main/resources/datawave/query/KeywordExtractionQueryLogicFactory.xml
Labels: Integration Tested, linked

#2943 Extract Kryo to member variable in CountQueryIterator
  warehouse/query-core/src/main/java/datawave/next/CountQueryIterator.java
Labels: DocumentScheduler

#2942 Type now supports Kryo serialization
  core/cached-results/pom.xml
  core/utils/type-utils/pom.xml
  core/utils/type-utils/src/main/java/datawave/data/type/BaseType.java
  core/utils/type-utils/src/main/java/datawave/data/type/DateType.java
  core/utils/type-utils/src/main/java/datawave/data/type/GeoLatType.java
  core/utils/type-utils/src/main/java/datawave/data/type/GeoLonType.java
  core/utils/type-utils/src/main/java/datawave/data/type/HexStringType.java
  core/utils/type-utils/src/main/java/datawave/data/type/LcNoDiacriticsListType.java
  core/utils/type-utils/src/main/java/datawave/data/type/LcNoDiacriticsType.java
  core/utils/type-utils/src/main/java/datawave/data/type/LcType.java
  core/utils/type-utils/src/main/java/datawave/data/type/NumberListType.java
  core/utils/type-utils/src/main/java/datawave/data/type/NumberType.java
  core/utils/type-utils/src/main/java/datawave/data/type/PointType.java
  core/utils/type-utils/src/main/java/datawave/data/type/Type.java
  core/utils/type-utils/src/main/java/datawave/data/type/util/Point.java
  warehouse/ingest-core/src/main/java/datawave/IdentityDataType.java
  warehouse/query-core/src/main/java/datawave/query/attributes/TypeAttribute.java
  warehouse/query-core/src/test/java/datawave/query/attributes/DocumentTest.java
  warehouse/query-core/src/test/java/datawave/query/attributes/TypeAttributeIT.java
  warehouse/query-core/src/test/java/datawave/query/attributes/it/DateTypeAttributeIT.java
  warehouse/query-core/src/test/java/datawave/query/attributes/it/GeoLatTypeAttributeIT.java
  warehouse/query-core/src/test/java/datawave/query/attributes/it/GeoLonTypeAttributeIT.java
  warehouse/query-core/src/test/java/datawave/query/attributes/it/HexTypeAttributeIT.java
  warehouse/query-core/src/test/java/datawave/query/attributes/it/LcNoDiacriticsListTypeAttributeIT.java
  warehouse/query-core/src/test/java/datawave/query/attributes/it/NumberListTypeAttributeIT.java
  warehouse/query-core/src/test/java/datawave/query/attributes/it/NumberTypeAttributeIT.java
  warehouse/query-core/src/test/java/datawave/query/attributes/it/PointTypeAttributeIT.java
Labels: Integration Tested

#2766 Adding utf8 charset conversions
  microservices/services/accumulo/api/src/main/java/datawave/webservice/request/objects/ReferencedValue.java
  microservices/services/audit/service/src/main/java/datawave/microservice/audit/auditors/file/FileAuditor.java
  warehouse/core/src/test/java/datawave/util/TextUtilTest.java
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/BulkIngestCounters.java
  warehouse/query-core/src/main/java/datawave/core/iterators/FieldIndexDocumentFilter.java
  warehouse/query-core/src/test/java/datawave/query/MixedGeoAndGeoWaveTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/nodes/ExceededOrThresholdMarkerJexlNodeTest.java
  warehouse/query-core/src/test/java/datawave/query/planner/CompositeIndexTest.java
  warehouse/query-core/src/test/java/datawave/query/planner/GeoSortedQueryDataTest.java
  warehouse/query-core/src/test/java/datawave/query/planner/MultiValueCompositeIndexTest.java
  warehouse/query-core/src/test/java/datawave/query/tables/RemoteEdgeQueryLogicHttpTest.java
  warehouse/query-core/src/test/java/datawave/query/tables/RemoteEventQueryLogicHttpTest.java
  web-services/common/src/main/java/datawave/webservice/common/remote/RemoteHttpService.java
Labels: Integration Tested

#2982 DocumentScheduler now supports composite fields
  warehouse/query-core/src/main/java/datawave/next/retrieval/DocumentIterator.java
  warehouse/query-core/src/main/java/datawave/next/retrieval/DocumentIteratorOptions.java
  warehouse/query-core/src/main/java/datawave/query/predicate/ValueToAttributes.java
  warehouse/query-core/src/test/java/datawave/query/ShapesTest.java
Labels: Integration Tested, DocumentScheduler

#2976 Improve performance of TypeAttribute hashcode method
  warehouse/query-core/src/main/java/datawave/query/attributes/TypeAttribute.java
  warehouse/query-core/src/test/java/datawave/query/attributes/DocumentTest.java
  warehouse/query-core/src/test/java/datawave/query/attributes/TypeAttributeTest.java
  warehouse/query-core/src/test/java/datawave/query/attributes/it/DateTypeAttributeIT.java
  warehouse/query-core/src/test/java/datawave/query/attributes/it/GeoLatTypeAttributeIT.java
  warehouse/query-core/src/test/java/datawave/query/attributes/it/GeoLonTypeAttributeIT.java
  warehouse/query-core/src/test/java/datawave/query/attributes/it/HexTypeAttributeIT.java
  warehouse/query-core/src/test/java/datawave/query/attributes/it/IpAddressTypeAttributeIT.java
  warehouse/query-core/src/test/java/datawave/query/attributes/it/LcNoDiacriticsListTypeAttributeIT.java
  warehouse/query-core/src/test/java/datawave/query/attributes/it/LcNoDiacriticsTypeAttributeIT.java
  warehouse/query-core/src/test/java/datawave/query/attributes/it/LcTypeAttributeIT.java
  warehouse/query-core/src/test/java/datawave/query/attributes/it/NoOpTypeAttributeIT.java
  warehouse/query-core/src/test/java/datawave/query/attributes/it/NumberListTypeAttributeIT.java
  warehouse/query-core/src/test/java/datawave/query/attributes/it/NumberTypeAttributeIT.java
  warehouse/query-core/src/test/java/datawave/query/attributes/it/PointTypeAttributeIT.java
Labels: Integration Tested

#2986 Attribute cache computation of hashcode and sizeInBytes
  warehouse/query-core/src/main/java/datawave/query/attributes/Attribute.java
  warehouse/query-core/src/main/java/datawave/query/attributes/Attributes.java
  warehouse/query-core/src/main/java/datawave/query/attributes/Content.java
  warehouse/query-core/src/main/java/datawave/query/attributes/Geometry.java
  warehouse/query-core/src/main/java/datawave/query/attributes/IpAddress.java
  warehouse/query-core/src/main/java/datawave/query/attributes/Numeric.java
  warehouse/query-core/src/main/java/datawave/query/attributes/PreNormalizedAttribute.java
  warehouse/query-core/src/main/java/datawave/query/attributes/TypeAttribute.java
  warehouse/query-core/src/main/java/datawave/query/common/grouping/GroupingAttribute.java
  warehouse/query-core/src/main/java/datawave/query/jexl/JexlASTHelper.java
  warehouse/query-core/src/test/java/datawave/query/attributes/AttributeIT.java
  warehouse/query-core/src/test/java/datawave/query/attributes/DocumentTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/JexlASTHelperTest.java
Labels: Integration Tested
