Repository NationalSecurityAgency/datawave, pull requests merged in 2025-08, with the labels that each got.

#2589 Lossy Numeric Regex
  core/utils/type-utils/src/main/java/datawave/data/normalizer/GeoNormalizer.java
  core/utils/type-utils/src/main/java/datawave/data/normalizer/NumberNormalizer.java
  warehouse/ingest-core/src/main/java/datawave/IdentityDataType.java
  warehouse/query-core/src/main/java/datawave/query/jexl/lookups/ShardIndexQueryTableStaticMethods.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ExpandMultiNormalizedTerms.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/RegexIndexExpansionVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/UnfieldedIndexExpansionVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/UniqueExpressionTermsVisitor.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/test/java/datawave/query/NumericListQueryTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/nodes/QueryPropertyMarkerTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ExecutableExpansionVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ExpandMultiNormalizedTermsTest.java
  warehouse/query-core/src/test/java/datawave/query/util/WiseGuysIngest.java
Labels: Integration Tested

#3086 Updated Visitor function to avoid modifying config as it needs to remain
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/PushdownLargeFieldedListsVisitor.java
  warehouse/query-core/src/main/java/datawave/query/tables/async/event/VisitorFunction.java
Labels: Integration Tested

#3104 Updated to avoid moving to far when yielding
  warehouse/query-core/src/main/java/datawave/core/iterators/DatawaveFieldIndexCachingIteratorJexl.java
  warehouse/query-core/src/main/java/datawave/query/iterator/logic/AndIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/logic/DocumentAggregatingIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/logic/OrIterator.java
  warehouse/query-core/src/main/java/datawave/query/iterator/pipeline/PipelineIterator.java
Labels: Integration Tested

#3030 Dependabot dnsjava-2 version updates
  core/connection-pool/pom.xml
  pom.xml
  web-services/pom.xml
Labels: Integration Tested

#3115 Data Dictionary Help Menu
  microservices/services/dictionary/service/src/main/frontend/src/functions/components.ts
  microservices/services/dictionary/service/src/main/frontend/src/pages/DataDictionary.vue
  microservices/services/dictionary/service/src/main/frontend/src/pages/HelpMenu.vue
  microservices/services/dictionary/service/src/main/java/datawave/microservice/dictionary/DataDictionaryControllerLogic.java
  microservices/services/dictionary/service/src/main/java/datawave/microservice/dictionary/DataDictionaryControllerV2.java
  microservices/services/dictionary/service/src/main/java/datawave/microservice/dictionary/config/DataDictionaryProperties.java
Labels: Integration Tested

#3088 validation - new rule to interpret grouped fielded phases
  warehouse/query-core/src/main/java/datawave/query/lucene/visitors/GroupedInterpretationVisitor.java
  warehouse/query-core/src/main/java/datawave/query/rules/GroupedInterpretationRule.java
  warehouse/query-core/src/test/java/datawave/query/lucene/visitors/GroupedInterpretationVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/rules/GroupedInterpretationRuleTest.java
  warehouse/query-core/src/test/java/datawave/query/rules/ShardQueryRuleTest.java
  warehouse/query-core/src/test/java/datawave/query/tables/ShardQueryLogicQueryValidationTest.java
  warehouse/query-core/src/test/resources/datawave/query/QueryLogicFactory.xml
  web-services/deploy/configuration/src/main/resources/datawave/query/QueryLogicFactory.xml
Labels: linked

#3106 Remember previously assigned shardId
  warehouse/ingest-core/src/main/java/datawave/ingest/data/RawRecordContainer.java
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/shard/ShardIdFactory.java
  warehouse/ingest-core/src/test/java/datawave/ingest/mapreduce/handler/facet/FacetHandlerTest.java
  warehouse/ingest-core/src/test/java/datawave/ingest/mapreduce/handler/shard/ShardIdFactoryTest.java
Labels: Integration Tested, linked
