Repository NationalSecurityAgency/datawave, pull requests merged in 2025-09, with the labels that each got.

#3133 remove universal set
  core/common-util/src/main/java/datawave/core/common/util/TypeFilter.java
  core/common-util/src/test/java/datawave/core/common/util/TypeFilterTest.java
  core/utils/metadata-utils/src/main/java/datawave/query/util/MetadataHelper.java
  core/utils/metadata-utils/src/main/java/datawave/util/UniversalSet.java
  core/utils/metadata-utils/src/test/java/datawave/query/util/MetadataHelperTableTest.java
  core/utils/metadata-utils/src/test/java/datawave/util/UniversalSetTest.java
  warehouse/query-core/src/main/java/datawave/core/iterators/BoundedRangeExpansionIterator.java
  warehouse/query-core/src/main/java/datawave/core/iterators/FieldExpansionIterator.java
  warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java
  warehouse/query-core/src/main/java/datawave/query/index/lookup/DataTypeFilter.java
  warehouse/query-core/src/main/java/datawave/query/iterator/QueryOptions.java
  warehouse/query-core/src/main/java/datawave/query/iterators/FieldIndexCountingIterator.java
  warehouse/query-core/src/main/java/datawave/query/jexl/lookups/BoundedRangeIndexLookup.java
  warehouse/query-core/src/main/java/datawave/query/jexl/lookups/FieldExpansionIndexLookup.java
  warehouse/query-core/src/main/java/datawave/query/jexl/lookups/ShardIndexQueryTableStaticMethods.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/IteratorBuildingVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/PushdownUnexecutableNodesVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/SatisfactionVisitor.java
  warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
  warehouse/query-core/src/main/java/datawave/query/predicate/Projection.java
  warehouse/query-core/src/main/java/datawave/query/tables/ShardIndexQueryTable.java
  warehouse/query-core/src/main/java/datawave/query/tables/async/event/VisitorFunction.java
  warehouse/query-core/src/main/java/datawave/query/tables/facets/FacetedVisitor.java
  warehouse/query-core/src/main/java/datawave/query/tld/TLDIndexBuildingVisitor.java
  warehouse/query-core/src/test/java/datawave/query/config/ShardQueryConfigurationTest.java
  warehouse/query-core/src/test/java/datawave/query/function/DocumentProjectionTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ExecutableDeterminationVisitorTest.java
  warehouse/query-core/src/test/java/datawave/query/predicate/ProjectionTest.java
  warehouse/query-core/src/test/java/datawave/query/util/MultiNormalizerTest.java
Labels: Integration Tested, linked

#3161 Add new IndexLookups
  warehouse/query-core/src/main/java/datawave/query/jexl/lookups/AsyncIndexLookup.java
  warehouse/query-core/src/main/java/datawave/query/jexl/lookups/BaseRegexIndexLookup.java
  warehouse/query-core/src/main/java/datawave/query/jexl/lookups/BoundedRangeIndexLookup.java
  warehouse/query-core/src/main/java/datawave/query/jexl/lookups/FieldedRegexIndexLookup.java
  warehouse/query-core/src/main/java/datawave/query/jexl/lookups/IndexLookupMap.java
  warehouse/query-core/src/main/java/datawave/query/jexl/lookups/UnfieldedRegexIndexLookup.java
  warehouse/query-core/src/test/java/datawave/query/jexl/lookups/BaseIndexLookupTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/lookups/FieldExpansionIndexLookupTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/lookups/FieldedRegexIndexLookupTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/lookups/UnfieldedRegexIndexLookupTest.java
Labels: no-downstream-affects

#3171 Fix formatting in ShardReindexMapperTest
  warehouse/ingest-core/src/test/java/datawave/ingest/mapreduce/job/reindex/ShardReindexMapperTest.java
Labels: no-downstream-affects

#3191 Integrate new IndexLookups
  pom.xml
  warehouse/query-core/src/main/java/datawave/core/iterators/FieldedRegexExpansionIterator.java
  warehouse/query-core/src/main/java/datawave/core/iterators/UnfieldedRegexExpansionIterator.java
  warehouse/query-core/src/main/java/datawave/query/jexl/lookups/FieldedRegexIndexLookup.java
  warehouse/query-core/src/main/java/datawave/query/jexl/lookups/UnfieldedRegexIndexLookup.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/BaseIndexExpansionVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/RegexIndexExpansionVisitor.java
  warehouse/query-core/src/main/java/datawave/query/jexl/visitors/UnfieldedIndexExpansionVisitor.java
  warehouse/query-core/src/test/java/datawave/query/jexl/lookups/BaseIndexLookupTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/lookups/FieldedRegexIndexLookupTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/lookups/UnfieldedRegexIndexLookupTest.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/RegexIndexExpansionVisitorIT.java
  warehouse/query-core/src/test/java/datawave/query/jexl/visitors/UnfieldedIndexExpansionVisitorIT.java
Labels: Integration Tested

#3189 Replace deprecated new Integer()
  core/utils/type-utils/src/test/java/datawave/webservice/query/data/ObjectSizeOfTest.java
  warehouse/query-core/src/main/java/datawave/core/iterators/IteratorThreadPoolManager.java
  warehouse/query-core/src/main/java/datawave/query/tracking/ActiveQuery.java
  warehouse/query-core/src/test/java/datawave/query/tables/ProducerConsumerBufferTest.java
  warehouse/query-core/src/test/java/datawave/query/tables/ScannerSessionTest.java
Labels: no-downstream-affects

#3066 Remove parameters that are not used from BulkIngestMapFileLoader and start script
  warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/BulkIngestMapFileLoader.java
  warehouse/ingest-core/src/test/java/datawave/ingest/mapreduce/job/BulkIngestMapFileLoaderTest.java
  warehouse/ingest-scripts/src/main/resources/bin/ingest/map-file-bulk-loader.sh
Labels: no-downstream-affects

#3204 Set maven path in runner setup so dont need to here
  .github/workflows/compose-tests.yml
  .github/workflows/datawave-tests.yml
  .github/workflows/microservice-tests.yml
Labels: no-downstream-affects

#3205 Updated the metadata scanner to avoid using the WholeRowIterator which
  microservices/services/dictionary/service/src/main/java/datawave/microservice/metadata/DefaultMetadataFieldScanner.java
Labels: Integration Tested

#3209 NumericalEncoder now uses ThreadLocal NumberFormat
  core/utils/type-utils/src/main/java/datawave/data/type/util/NumericalEncoder.java
  core/utils/type-utils/src/test/java/datawave/data/type/util/NumericalEncoderTest.java
Labels: Integration Tested

#3210 ThreadLocal formatter for GeoUtils and GeoNormalizer
  core/utils/type-utils/src/main/java/datawave/data/normalizer/GeoNormalizer.java
  core/utils/type-utils/src/test/java/datawave/data/normalizer/GeoNormalizerTest.java
  warehouse/query-core/src/main/java/datawave/query/util/GeoUtils.java
  warehouse/query-core/src/test/java/datawave/query/util/GeoUtilsTest.java
Labels: Integration Tested
